import * as THREE from './three.module.js';
import {LANDMARKS,WORLD_MIN,WORLD_MAX,HEIGHT,overlaps,trace} from './world.js';
import {promenadeX,roadContains} from './city-layout.js';
import {safeLanding} from './map-travel.js';
import {updateDrive,DRIVE_MODES,vehicleContact,vehiclePenetration} from './vehicle-dynamics.js';
import {nanpuFloor} from './bridge-road.js';

export function createCommute({scene,world,civil,activity,getPos,blocked,exitBlocked=blocked,place,setView,turnView,notify,onExit=()=>{},allowed=()=>true,getActors=()=>[],onImpact=()=>{}}){
 const root=new THREE.Group();root.name='player-commuting';scene.add(root);const vehicles=[],box=new THREE.BoxGeometry(1,1,1);let ride=null;
 function cube(parent,color,x,y,z,sx,sy,sz){const m=new THREE.Mesh(box,new THREE.MeshLambertMaterial({color}));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.userData.range=220;parent.add(m);return m;}
 function groundVehicle(kind,p){const group=new THREE.Group();group.name='rideable-'+kind;group.position.set(p.x,p.y,p.z);root.add(group);const bicycle=kind==='bicycle',color=bicycle?'#62d3c1':'#e4af4f',wheels=[],steerRigs=[];
  function wheel(x,z){const pivot=new THREE.Group();pivot.position.set(x,bicycle?.34:.28,z);group.add(pivot);const spin=new THREE.Group();pivot.add(spin);const tire=new THREE.Mesh(bicycle?new THREE.TorusGeometry(.32,.055,5,12):new THREE.CylinderGeometry(.28,.28,.2,10),new THREE.MeshLambertMaterial({color:'#263540'}));if(bicycle)tire.rotation.y=Math.PI/2;else tire.rotation.z=Math.PI/2;spin.add(tire);cube(spin,'#adbac0',0,0,0,bicycle?.055:.22,.05,bicycle?.54:.42);wheels.push(spin);if(z<0)steerRigs.push(pivot);return pivot;}
  if(bicycle){wheel(0,.65);const front=wheel(0,-.65);cube(group,color,0,.62,0,.1,.1,1.3);cube(group,color,0,.8,.2,.1,.5,.1);cube(group,'#243848',0,1.05,.2,.3,.08,.35);cube(front,color,0,.66,.07,.07,.75,.07);cube(front,'#435962',0,1.03,.05,.6,.07,.07);
  }else{cube(group,color,0,.5,0,1.6,.8,3.2);cube(group,'#769eaf',0,1.08,0,1.38,.65,1.65);cube(group,color,0,1.43,0,1.45,.12,1.8);for(const x of [-.83,.83])for(const z of [-1,1])wheel(x,z);for(const x of [-.5,.5])cube(group,'#fff0b4',x,.65,-1.63,.28,.2,.06);}
  let pilot;if(bicycle){pilot=new THREE.Group();cube(pilot,'#f2dc97',0,1.48,.12,.42,.52,.28);cube(pilot,'#dfb28d',0,1.9,.06,.31,.31,.3);cube(pilot,'#eef1ed',0,2.08,.06,.38,.16,.36);for(const side of [-1,1]){cube(pilot,'#40586b',side*.15,.96,.12,.16,.55,.2);const arm=cube(pilot,'#f2dc97',side*.22,1.47,-.2,.13,.47,.15);arm.rotation.x=-.8;}group.add(pilot);pilot.visible=false;}
  const v={kind,root:group,pilot,wheels,steerRigs,speed:0,throttle:0,steering:0,steerAngle:0,gear:2,yaw:0,halfWidth:bicycle?.42:.88,halfLength:bicycle?.8:1.65,maxSpeed:bicycle?11:19};vehicles.push(v);return v;
 }
 function parking(kind,x,z){const width=kind==='car'?.88:.42,length=kind==='car'?1.65:.8;return safeLanding(world,{x,y:26,z},(x,y,z)=>{
  for(const dx of [-width,0,width])for(const dz of [-length,0,length])if(roadContains(x+dx,z+dz)||blocked(x+dx,y,z+dz)||!world.get(Math.floor(x+dx),25,Math.floor(z+dz)))return true;
  return vehicles.some(v=>vehicleContact({root:{},halfWidth:width,halfLength:length},x,y,z,0,v));
 });}
 for(const z of [99,162]){const p=parking('bicycle',promenadeX(z)-6,z+5);if(p)groundVehicle('bicycle',p);}
 for(const z of [99,192]){const p=parking('car',promenadeX(z)-12,z+9);if(p)groundVehicle('car',p);}
 for(const [kind,x,z]of [['bicycle',184,52],['car',224,37]]){const p=parking(kind,x,z);if(p)groundVehicle(kind,p);}
 const heli={kind:'helicopter',root:activity.heli,speed:0,yaw:0,halfWidth:1.15,halfLength:2.1,maxSpeed:24};vehicles.push(heli);const home=heli.root.position.clone();
 function exitPoint(){if(!ride)return null;const v=ride.vehicle,p=v.root.position,a=v.root.rotation.y,isHeli=ride.kind==='helicopter',bridge=nanpuFloor(world,p.x,p.z),base=bridge??Math.round(p.y),levels=isHeli?[base,base-1]:[base];
  const footprint={root:{},halfWidth:.3,halfLength:.3},clear=(x,y,z)=>{const dx=x-p.x,dz=z-p.z,side=dx*Math.cos(a)-dz*Math.sin(a),long=dx*Math.sin(a)+dz*Math.cos(a);return !exitBlocked(x,y,z)&&!actors().some(o=>o.root!==v.root&&vehicleContact(footprint,x,y,z,0,o))&&!(Math.abs(side)<v.halfWidth+.7&&Math.abs(long)<v.halfLength+.7)&&!(isHeli&&Math.abs(side)<.8&&long>1&&long<6.2);};
  const piloted=v.root.userData.piloted;v.root.userData.piloted=false;try{for(const y of levels){if(isHeli&&Math.abs(y-p.y)>1.15)continue;for(const side of [1,-1]){const x=p.x+Math.cos(a)*side*(isHeli?2.8:v.halfWidth+1),z=p.z-Math.sin(a)*side*(isHeli?2.8:v.halfWidth+1);if(clear(x,y,z)&&overlaps(world,x,y-.1,z))return {x,y,z};}const point=safeLanding(world,{x:p.x,y,z:p.z},(x,y,z)=>!clear(x,y,z));if(point)return point;}}finally{v.root.userData.piloted=piloted;}return null;
 }
 function end(force=false){if(!ride)return true;const point=exitPoint();if(!point&&!force){notify(ride.kind==='helicopter'?'先用 Shift 降落到地面或停机坪，再按 V 离开。':'这里不能安全下车，请移动到开阔位置。');return false;}const old=ride;ride=null;old.vehicle.root.userData.piloted=false;if(old.vehicle.pilot)old.vehicle.pilot.visible=false;old.vehicle.speed=0;old.vehicle.throttle=0;old.vehicle.root.rotation.x=0;old.vehicle.root.rotation.z=0;if(point){place(point);setView(Math.atan2(old.vehicle.root.position.x-point.x,old.vehicle.root.position.z-point.z),-.12);}else if(force)place(old.from);if(old.kind==='helicopter'&&!point){heli.root.position.copy(home);heli.yaw=0;heli.root.rotation.set(0,0,0);}onExit();notify('已下车 / 离开载具');return true;}
 function mount(v){if(!allowed()){notify('跑酷中不能搭乘载具；按 V 退出挑战。');return false;}ride={kind:v.kind,vehicle:v,from:{...getPos()}};v.root.userData.piloted=true;if(v.pilot)v.pilot.visible=true;v.yaw=v.root.rotation.y;if(v.kind==='bus')v.lastPosition=v.root.position.clone();setView(v.yaw,-.22);notify(v.kind==='bus'?'已上公交 · 沿线路自动行驶 · V 下车':v.kind==='helicopter'?'直升机 · W/S 前后 · A/D 转向 · 空格上升 · Shift 下降 · V 降落后离开':'W/S 前进 / 刹车倒车 · A/D 转向 · V 下车');return true;}
 function use(){if(ride){end();return true;}const p=getPos(),nearest=vehicles.filter(v=>Math.abs(p.y-v.root.position.y)<3&&Math.hypot(p.x-v.root.position.x,p.z-v.root.position.z)<3.2).sort((a,b)=>pDistance(a,p)-pDistance(b,p))[0];if(nearest){mount(nearest);return true;}const bus=civil.traffic.buses.find(b=>Math.abs(p.y-b.root.position.y)<3&&pDistance(b,p)<4.8);if(bus){if(bus.dwell>0)mount({...bus,kind:'bus'});else notify('请在公交停站时靠近车门按 V 上车。');return true;}return false;}
 function pDistance(v,p){return Math.hypot(p.x-v.root.position.x,p.z-v.root.position.z);}
 function actors(){return [...getActors(),...vehicles];}
 function actorClear(v,x,y,z,a){const p=v.root.position;return actors().every(o=>{const next=vehiclePenetration(v,x,y,z,a,o),current=vehiclePenetration(v,p.x,p.y,p.z,v.yaw,o),q=o.root.position;return next<=0||next<current-1e-9||current>0&&next<=current+1e-9&&(x-q.x)**2+(z-q.z)**2>(p.x-q.x)**2+(p.z-q.z)**2;});}
 function bodyClear(v,x,y,z,a=v.yaw){if(x<WORLD_MIN+3||x>WORLD_MAX-3||z<WORLD_MIN+3||z>WORLD_MAX-3)return false;for(const dx of [-v.halfWidth,0,v.halfWidth])for(const dz of [-v.halfLength,0,v.halfLength]){const xx=x+dx*Math.cos(a)+dz*Math.sin(a),zz=z-dx*Math.sin(a)+dz*Math.cos(a),h=v.kind==='helicopter'?null:nanpuFloor(world,xx,zz),probe=h!==null&&Math.abs(y-h)<1.5?Math.max(y,Math.ceil(h)):y;if(blocked(xx,probe,zz)||v.kind==='helicopter'&&overlaps(world,xx,y+1.5,zz))return false;}return actorClear(v,x,y,z,a);}
 function actorAt(v,x,y,z,a){return actors().find(o=>vehicleContact(v,x,y,z,a,o));}
 function hit(v,x,y,z,a){const speed=Math.abs(v.speed),actor=actorAt(v,x,y,z,a);if((v.impactCooldown??0)<=0&&speed>.35){v.shock=Math.min(.9,speed*.09);v.impactCooldown=.45;const sign=Math.sign(v.speed);if(actor)onImpact(actor,-Math.sin(a)*sign,-Math.cos(a)*sign,speed);notify(actor?.person?'撞到行人，已急刹；请减速让行。':actor?'发生车辆碰撞，请减速绕行。':'碰到障碍，松开油门或倒车调整方向。');}v.speed=actor?.person?0:-v.speed*.12;v.throttle=0;}
 function moveGround(v,dt,keys){let remaining=dt;while(remaining>0){const step=Math.min(remaining,1/120);remaining-=step;const before=v.root.position.clone(),{yawDelta,distance}=updateDrive(v,step,keys),a=v.yaw+yawDelta,p=v.root.position;
   // Apply rotation before translation so a blocked forward step does not discard steering.
   if(bodyClear(v,p.x,p.y,p.z,a)){v.yaw=a;v.root.rotation.y=a;turnView(yawDelta);}
   const x=p.x-Math.sin(v.yaw)*distance,z=p.z-Math.cos(v.yaw)*distance;
   const bridge=nanpuFloor(world,x,z),y=[...(bridge!==null&&Math.abs(p.y-bridge)<1.5?[bridge]:[]),p.y,p.y+1,p.y-1,p.y-2].find(y=>bodyClear(v,x,y,z,v.yaw)&&[-v.halfWidth,v.halfWidth].every(side=>{const xx=x+Math.cos(v.yaw)*side,zz=z-Math.sin(v.yaw)*side,h=nanpuFloor(world,xx,zz);return h!==null&&Math.abs(h-y)<1.5||world.get(Math.floor(xx),Math.round(y)-1,Math.floor(zz));}));
   if(y===undefined){if(Math.abs(distance)>.00001)hit(v,x,p.y,z,v.yaw);}else p.set(x,y,z);
   const travel=p.distanceTo(before)*Math.sign(distance);for(const wheel of v.wheels)wheel.rotation.x-=travel/(v.kind==='bicycle'?.32:.28);
  }
  for(const rig of v.steerRigs)rig.rotation.y=v.steerAngle;v.shock=THREE.MathUtils.damp(v.shock??0,0,7,dt);const p=v.root.position,front=nanpuFloor(world,p.x-Math.sin(v.yaw),p.z-Math.cos(v.yaw)),back=nanpuFloor(world,p.x+Math.sin(v.yaw),p.z+Math.cos(v.yaw)),slope=front!==null&&back!==null?Math.atan2(front-back,2):0;v.root.rotation.x=slope+(v.brake?-.045:v.throttle*.025)+Math.sin((v.shock??0)*30)*(v.shock??0)*.05;v.root.rotation.z=v.kind==='bicycle'?-v.steering*Math.min(.12,Math.abs(v.speed)*.018):0;
 }
 function moveHeli(v,dt,keys){const steer=(Number(keys.has('KeyA'))-Number(keys.has('KeyD')))*dt*1.1,a=v.yaw+steer,p=v.root.position,up=Number(keys.has('Space'))-Number(keys.has('ShiftLeft')||keys.has('ShiftRight')),throttle=Number(keys.has('KeyW'))-Number(keys.has('KeyS'));v.speed=THREE.MathUtils.damp(v.speed,throttle*v.maxSpeed,2,dt);const n=Math.max(1,Math.ceil((Math.abs(v.speed)+9)*dt/.2)),step=dt/n;for(let i=0;i<n;i++){const y=Math.min(HEIGHT+8,Math.max(26,p.y+up*9*step));if(bodyClear(v,p.x,y,p.z,a))p.y=y;const x=p.x-Math.sin(a)*v.speed*step,z=p.z-Math.cos(a)*v.speed*step;if(bodyClear(v,x,p.y,z,a))p.set(x,p.y,z);else v.speed=0;}if(bodyClear(v,p.x,p.y,p.z,a)){v.yaw=a;v.root.rotation.y=a;turnView(steer);}}

 function tick(dt,keys=new Set()){if(ride){ride.dt=dt;ride.shakePhase=(ride.shakePhase??0)+dt*32;const v=ride.vehicle;if(v.kind==='helicopter'){moveHeli(v,dt,keys);for(const blade of v.root.children.filter(o=>o.scale?.y===.09))blade.rotation.y+=dt*20;}else if(v.kind!=='bus')moveGround(v,dt,keys);else if(dt>0){v.travelSpeed=v.root.position.distanceTo(v.lastPosition)/dt;v.lastPosition.copy(v.root.position);const a=v.root.rotation.y;turnView(THREE.MathUtils.euclideanModulo(a-v.yaw+Math.PI,Math.PI*2)-Math.PI);v.yaw=a;}const p=v.root.position;place({x:p.x,y:p.y+1.1,z:p.z});}const p=getPos(),near=vehicles.find(v=>Math.abs(p.y-v.root.position.y)<3&&pDistance(v,p)<3.2),bus=civil.traffic.buses.find(b=>b.dwell>0&&Math.abs(p.y-b.root.position.y)<3&&pDistance(b,p)<4.8);const label=ride?({bicycle:'骑行',car:'驾车',bus:'公交乘客',helicopter:'直升机飞行'}[ride.kind]):'';return ride?`${label}${['bicycle','car'].includes(ride.kind)?' · '+DRIVE_MODES[(ride.vehicle.gear??2)-1]:''} · ${Math.round(Math.abs(ride.kind==='bus'?(ride.vehicle.travelSpeed??0):(ride.vehicle.speed??0))*3.6)} km/h${['bicycle','car'].includes(ride.kind)?' · 空格刹车 · 1/2/3 配速':''} · V 离开`:near?'V '+({bicycle:'骑上自行车',car:'驾驶汽车',helicopter:'驾驶白玉兰直升机'}[near.kind]):bus?'V 搭乘公交车':'';}
 function cameraPose(yaw,pitch){if(!ride)return null;ride.cameraYaw??=yaw;ride.cameraYaw+=Math.atan2(Math.sin(yaw-ride.cameraYaw),Math.cos(yaw-ride.cameraYaw))*(1-Math.exp(-8*(ride.dt??1/60)));yaw=ride.cameraYaw;const p=ride.vehicle.root.position,focus={x:p.x,y:p.y+1.6+Math.sin(ride.shakePhase??0)*(ride.vehicle.shock??0)*.13,z:p.z},distance=ride.kind==='helicopter'?12:6;const wanted=new THREE.Vector3(p.x+Math.sin(yaw)*distance,p.y+2.8-Math.sin(pitch)*distance,p.z+Math.cos(yaw)*distance),origin=new THREE.Vector3(focus.x,focus.y,focus.z),direction=wanted.clone().sub(origin).normalize(),hit=trace(world,origin,direction,wanted.distanceTo(origin));if(hit){const reach=Math.max(.3,new THREE.Vector3(hit.x+.5,hit.y+.5,hit.z+.5).distanceTo(origin)-1);wanted.copy(origin).addScaledVector(direction,reach);}
  // A rooftop wall can shorten the follow camera into the helicopter's opaque cabin.
  if(ride.kind==='helicopter'&&(wanted.distanceTo(origin)<5||overlaps(world,wanted.x,wanted.y,wanted.z))){for(const [dx,dy,dz]of [[0,9,0],[6,7,0],[-6,7,0],[0,7,6],[0,7,-6]]){const candidate=new THREE.Vector3(p.x+dx,p.y+dy,p.z+dz),ray=candidate.clone().sub(origin);if(!overlaps(world,candidate.x,candidate.y,candidate.z)&&!trace(world,origin,ray.clone().normalize(),ray.length())){wanted.copy(candidate);break;}}}else if(overlaps(world,wanted.x,wanted.y,wanted.z))wanted.set(p.x,p.y+3.6,p.z);return {position:{x:wanted.x,y:wanted.y,z:wanted.z},focus};}

 return {vehicles,use,mount,end,tick,cameraPose,bodyClear,get ride(){return ride;},isRiding:()=>!!ride,safeSavePoint:()=>ride?exitPoint()||{...ride.from}:null,collides:(x,y,z)=>vehicles.some(v=>{if(v===ride?.vehicle||y>=v.root.position.y+1.6||y+1.75<=v.root.position.y)return false;const dx=x-v.root.position.x,dz=z-v.root.position.z,a=v.root.rotation.y;return Math.abs(dx*Math.cos(a)-dz*Math.sin(a))<v.halfWidth+.3&&Math.abs(dx*Math.sin(a)+dz*Math.cos(a))<v.halfLength+.3;})};
}
