import * as THREE from './three.module.js';
import {creatureStep} from './creature-movement.js';
import {SurvivalState,RECIPES,furnitureCollides,furnitureBounds} from './survival-state.js';
import {WATER_LEVEL,WORLD_MIN,WORLD_MAX,LANDMARKS,BLOCKS,overlaps,trace} from './world.js';
const $=id=>document.getElementById(id);
export function createLife({scene,world,notify,pause,resume,getPos,getDirection,getYaw=()=>0,blocked=(x,y,z)=>overlaps(world,x,y,z),isDry=()=>false,onMode,onHeld,onDeath,setDay,onProgress}){
 const state=new SurvivalState(),furnMeshes=[],animals=[],marine=[],enemies=[],berries=[],treasureMeshes=new Map();let enemyClock=0,hudClock=0,panel=null;
 const box=new THREE.BoxGeometry(1,1,1),materials=new Map();
 function mat(color,glow=false){const key=color+glow;if(!materials.has(key))materials.set(key,glow?new THREE.MeshBasicMaterial({color}):new THREE.MeshLambertMaterial({color}));return materials.get(key)}
 function cube(root,color,x,y,z,sx,sy,sz,glow=false){const m=new THREE.Mesh(box,mat(color,glow));m.position.set(x,y,z);m.scale.set(sx,sy,sz);root.add(m);return m;}
 function ground(x,z){const surface=world.surfaceAt(x,z);for(let y=surface+3;y>=Math.max(1,surface-4);y--)if(world.get(Math.floor(x),y-1,Math.floor(z))&&!world.get(Math.floor(x),y,Math.floor(z))&&!world.get(Math.floor(x),y+1,Math.floor(z)))return y;return surface;}
 function label(root,text,y,color='#e6ffaf'){const c=document.createElement('canvas');c.width=320;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='#183035dd';ctx.fillRect(0,0,320,64);ctx.fillStyle=color;ctx.textAlign='center';ctx.font='bold 24px sans-serif';ctx.fillText(text,160,42);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c)}));sp.position.y=y;sp.scale.set(3.2,.64,1);root.add(sp);return sp;}
 function furnitureModel(f){const root=new THREE.Group();root.position.set(f.x,f.y,f.z);root.rotation.y=f.rotation||0;root.userData.range=65;const legs=(y=.3)=>{for(const x of [-.32,.32])for(const z of [-.32,.32])cube(root,'#6c4b33',x,y,z,.13,y*2,.13)};
  if(f.type==='bed'){cube(root,'#8d603e',0,.18,0,.95,.35,1.7);cube(root,'#e98d9e',0,.43,.12,.92,.2,1.36);cube(root,'#fff5dc',0,.48,-.55,.87,.22,.4);cube(root,'#b18559',0,.45,-.85,1,.9,.12);}
  if(f.type==='chair'){legs();cube(root,'#c69b65',0,.65,0,.88,.15,.88);cube(root,'#9f7448',0,1,-.36,.88,.7,.15);}
  if(f.type==='table'){legs(.45);cube(root,'#ccac77',0,.95,0,1.3,.18,1.3);cube(root,'#f3e6ca',.2,1.08,.15,.38,.08,.38);}
  if(f.type==='lamp'){cube(root,'#637176',0,.1,0,.65,.18,.65);cube(root,'#786556',0,.85,0,.13,1.5,.13);cube(root,'#e6ffa5',0,1.55,0,.52,.55,.52,true);}
  if(f.type==='chest'){cube(root,'#b57b41',0,.4,0,1,.8,.85);cube(root,'#755239',0,.82,0,1.06,.15,.9);cube(root,'#ffd976',0,.57,.44,.14,.2,.06,true);}
  if(f.type==='campfire'){for(let i=0;i<6;i++){const a=i*Math.PI/3;cube(root,'#8a969b',Math.cos(a)*.38,.12,Math.sin(a)*.38,.32,.25,.32)}cube(root,'#805133',0,.23,0,.7,.2,.28);cube(root,'#ffb44e',0,.5,0,.3,.55,.3,true);cube(root,'#fff397',0,.72,0,.18,.28,.18,true);}
  if(f.type==='bookshelf'){cube(root,'#9c7348',0,.65,-.22,1.1,1.3,.16);for(const y of [.05,.65,1.3])cube(root,'#b38b5c',0,y,0,1.1,.12,.55);for(let i=0;i<6;i++)for(const y of [.35,.97])cube(root,['#cc687d','#90b782','#698ea9'][i%3],-.43+i*.17,y,0,.12,.47,.35);}
  if(f.type==='planter'){cube(root,'#aa8251',0,.22,0,1.1,.42,1.1);cube(root,'#664638',0,.44,0,1,.04,1);root.userData.crops=[];for(const x of [-.28,.28])for(const z of [-.28,.28])root.userData.crops.push(cube(root,'#b8d865',x,.7,z,.15,.55,.15));}
  if(['lamp','campfire'].includes(f.type)&&furnMeshes.filter(m=>['lamp','campfire'].includes(m.f.type)).length<6){const light=new THREE.PointLight(f.type==='lamp'?'#e5ffbd':'#ffad55',2.6,12,1.5);light.position.y=f.type==='lamp'?1.65:.8;root.add(light);}scene.add(root);furnMeshes.push({f,root});return root;
 }
 function animalModel(type){const root=new THREE.Group();const color=type==='sheep'?'#eae6d3':type==='pig'?'#ed9caa':'#fff5d4';const legs=[];if(type==='chicken'){cube(root,color,0,.35,0,.48,.55,.62);cube(root,color,0,.74,-.23,.3,.32,.3);cube(root,'#ffbe43',0,.7,-.43,.24,.14,.2);cube(root,'#e96661',0,.95,-.23,.13,.13,.2);for(const x of [-.14,.14])legs.push(cube(root,'#b08b40',x,.1,0,.07,.22,.07));}else{cube(root,color,0,.7,0,.85,.75,1.15);cube(root,type==='sheep'?'#79776c':color,0,.83,-.7,.5,.53,.46);if(type==='pig')cube(root,'#cb7f8e',0,.75,-.95,.35,.2,.15);for(const x of [-.29,.29])for(const z of [-.38,.38])legs.push(cube(root,type==='sheep'?'#827965':'#ad7180',x,.22,z,.17,.42,.17));}
  const eyey=type==='chicken'?.79:.92,eyex=type==='chicken'?.155:.26,eyez=type==='chicken'?-.32:-.8;for(const side of [-1,1])cube(root,'#21323a',side*eyex,eyey,eyez,.06,.08,.07);return {root,legs};
 }
 for(let i=0;i<26;i++){const region=i<10?[64+i*2.5,323+i%4*5]:i<18?[310+(i-10)*5,235+i%3*6]:[118+(i-18)*3,305+i%3*4];const type=['sheep','pig','chicken'][i%3],model=animalModel(type),x=region[0],z=region[1],y=ground(x,z);if(y<=WATER_LEVEL||world.protected(Math.floor(x),y,Math.floor(z)))continue;model.root.position.set(x,y,z);model.root.userData.range=70;scene.add(model.root);animals.push({...model,type,hp:2,heading:i*1.9,timer:i*.2,cooldown:0,origin:{x,z}});}
 // Fish, turtles and luminous jellyfish inhabit the deep-water garden.
 for(let i=0;i<32;i++){const root=new THREE.Group(),type=i%8===0?'turtle':i%7===0?'jelly':'fish';if(type==='fish'){cube(root,['#ffd877','#f4a6b6','#78dadd'][i%3],0,0,0,.18,.25,.7);cube(root,'#fcf2bb',0,0,.45,.38,.33,.16);for(const x of [-.1,.1])cube(root,'#17333b',x,.05,-.2,.05,.05,.06);}if(type==='turtle'){cube(root,'#4b947b',0,0,0,.75,.3,.95);cube(root,'#8dd1a0',0,0,-.61,.3,.24,.36);for(const x of [-.5,.5])for(const z of [-.3,.3])cube(root,'#89bfa0',x,-.06,z,.43,.1,.3);}if(type==='jelly'){cube(root,'#9bc7fa',0,0,0,.5,.25,.5,true);for(const x of [-.16,.16])for(const z of [-.16,.16])cube(root,'#bbbeff',x,-.45,z,.05,.65,.05,true);}scene.add(root);marine.push({root,type,cx:263+i*7%26,cz:275+i*11%42,y:12+i%7,phase:i});}
 for(const [id,p] of Object.entries({reef:{x:284.5,y:10,z:287.5},temple:{x:273.5,y:10,z:301.5},wreck:{x:294.5,y:8,z:276.5}})){const root=new THREE.Group();root.position.set(p.x,p.y,p.z);cube(root,'#b67e43',0,.3,0,.75,.6,.65);cube(root,'#e9ffa6',0,.68,0,.33,.14,.33,true);label(root,'G 海底宝箱',1.5);scene.add(root);treasureMeshes.set(id,{root,p});}
 const dock=new THREE.Group();dock.position.set(LANDMARKS.dock.x,LANDMARKS.dock.y,LANDMARKS.dock.z);cube(dock,'#f6cf72',0,.55,0,1.2,1.1,.8);cube(dock,'#657d8d',-.25,1.4,0,.3,.75,.3);cube(dock,'#8ae1ed',.3,1.3,0,.48,.3,.15,true);label(dock,'V 领取潜水套装',2.5);scene.add(dock);
 for(const [x,z] of [[66,328],[81,336],[313,239],[340,242],[124,307],[134,311]]){const root=new THREE.Group(),y=ground(x,z);if(y<WATER_LEVEL)continue;root.position.set(x+.5,y,z+.5);cube(root,'#4d874c',0,.4,0,.8,.8,.8);for(let i=0;i<4;i++)cube(root,'#ee8491',i%2*.5-.25,.5+Math.floor(i/2)*.25,-.45,.17,.17,.17);scene.add(root);berries.push({root,ready:0});}
 function distance(point){const p=getPos();return Math.hypot(point.x-p.x,point.y+.6-(p.y+1),point.z-p.z)}
 function visiblePoint(point){const p=getPos(),origin={x:p.x,y:p.y+1.62,z:p.z},v=new THREE.Vector3(point.x-origin.x,point.y+.65-origin.y,point.z-origin.z),length=v.length();v.normalize();if(trace(world,origin,v,Math.max(0,length-.2)))return false;for(let d=.45;d<length-.3;d+=.2)if(blocked(origin.x+v.x*d,origin.y+v.y*d-.65,origin.z+v.z*d))return false;return true;}
 function lit(point){return furnMeshes.some(m=>['lamp','campfire'].includes(m.f.type)&&Math.hypot(m.f.x-point.x,m.f.y-point.y,m.f.z-point.z)<8);}
 function aimed(root,reach=3.8){const p=getPos(),d=getDirection(),v=new THREE.Vector3(root.position.x-p.x,root.position.y+.65-p.y-1.62,root.position.z-p.z),dist=v.length();return dist<reach&&v.normalize().dot(d)>.68&&visiblePoint(root.position);}
 function closest(){const p=getPos();let out=[];for(const fm of furnMeshes)if(distance(fm.f)<3&&visiblePoint(fm.f))out.push({type:'furniture',data:fm,dist:distance(fm.f)});for(const a of animals)if(distance(a.root.position)<3&&visiblePoint(a.root.position))out.push({type:'animal',data:a,dist:distance(a.root.position)});for(const b of berries)if(distance(b.root.position)<2.6&&visiblePoint(b.root.position))out.push({type:'berry',data:b,dist:distance(b.root.position)});for(const [id,t] of treasureMeshes)if(!state.treasures.has(id)&&distance(t.p)<3&&visiblePoint(t.p))out.push({type:'treasure',id,data:t,dist:distance(t.p)});const origin=new THREE.Vector3(p.x,p.y+1.62,p.z),direction=getDirection();out=out.filter(item=>{const point=item.data.f||item.data.root.position;const v=new THREE.Vector3(point.x,point.y+.65,point.z).sub(origin);item.look=v.normalize().dot(direction);return item.look>.25||item.dist<1.4;});return out.sort((a,b)=>b.look-a.look||a.dist-b.dist)[0];}
 function changed(){onHeld(state.held);refresh();onProgress();}
 function refresh(){const goal=state.survivalGoals;$('survival-goal').hidden=!state.survival;$('survival-goal').textContent=`生存第 ${Math.floor(state.survivalSeconds/240)+1} 天 · ${state.survivalGoals.nights} 个平安夜
${goal.wood>=3?'✓':'□'} 采集木头 ${Math.min(3,goal.wood)}/3  ${state.pickaxe?'✓':'□'} 制作镐
${state.home?'✓':'□'} 设置床铺  ${goal.nights?'✓':'□'} 度过夜晚
C 制作 · G 采食 / 用床 · Z 进食 · Q 反击`;const counts=$('hotbar').children;for(let i=0;i<counts.length;i++){const n=counts[i].querySelector('.infinity');if(n)n.textContent=state.survival?state.bag[i+1]||0:'∞';}$('inventory-note').textContent=state.held?'手持家具 · E 放置 · C 收回':state.survival?'有限材料 · C 制作 / 背包':'无限材料 · C 家具 / 制作';$('vitals').hidden=!state.survival&&! (!isDry()&&getPos().y+1.62<WATER_LEVEL);$('vitals').textContent=`♥ ${Math.ceil(state.health)}/20  ·  饱食 ${Math.ceil(state.hunger)}/20  ·  氧气 ${Math.ceil(state.oxygen)}/${state.maxOxygen}${state.equipped?' · 潜水套装':''}`;$('survival-toggle').textContent=state.survival?'切换创造模式':'切换生存模式';$('craft-summary').textContent=`食物 ${state.food} · 生肉 ${state.raw} · 羊毛 ${state.wool} · 海珍珠 ${state.pearls} · ${state.pickaxe===2?'石镐':state.pickaxe===1?'木镐':'徒手采集'}${state.pickaxe?'（剩余 '+state.durability+' 次）':''} · ${state.glider?'已拥有滑翔伞':''} · ${state.sword?'已装备石剑':'徒手'} · ${state.equipped?'潜水套装已穿戴':state.dive?'潜水套装已拥有':'还没有潜水套装'}`;$('bag-summary').textContent=Array.from({length:12},(_,i)=>`${BLOCKS[i+1].name} ${state.bag[i+1]||0}`).join(' · ');}
 function open(id){if(panel)return;pause();panel=id;$(id).showModal();refresh();}
 function close(){if(!panel)return;$(panel).close();panel=null;resume();}
 function craft(){renderPacked();open('craft-dialog')}
 for(const [id,r] of Object.entries(RECIPES)){const b=document.createElement('button');b.className='recipe-card';const cost=Object.entries(r.cost).map(([k,n])=>`${BLOCKS[k].name}×${n}`).join(' + ')+(r.pearls?' + 海珍珠×'+r.pearls:'')+(r.wool?' + 羊毛×'+r.wool:'')+(r.food?' + 食物×'+r.food:'');b.textContent=r.name+'\n'+cost;b.onclick=()=>{if(state.craft(id)){changed();if(r.item){close();notify(r.name+'拿好了，瞄准地面按 E 放置。')}else notify('制作完成：'+r.name)}else notify(state.held&&r.item?'先放下或收回手中的家具。':'材料不足，或已经拥有此装备。')};$('recipes').appendChild(b);}
 $('craft-close').onclick=close;$('craft-button').onclick=craft;
 // Packed furnishings are represented by recipe credits, and can be taken out without spending again.
 const packed={};function packHeld(){if(state.held){packed[state.held]=(packed[state.held]||0)+1;state.held=null;changed();}}
 $('craft-stow').onclick=()=>{packHeld();renderPacked()};
 function renderPacked(){const container=$('packed-items');container.replaceChildren();for(const [type,n] of Object.entries(packed))if(n>0){const b=document.createElement('button');b.textContent=RECIPES[type].name+' ×'+n;b.onclick=()=>{if(state.held){notify('请先放置手中的家具');return;}packed[type]--;state.held=type;changed();close()};container.appendChild(b);}}
 $('craft-eat').onclick=()=>eat();$('dive-button').onclick=()=>dive();$('craft-dialog').addEventListener('cancel',e=>{e.preventDefault();close()});
 let activeChest=null;$('chest-close').onclick=close;$('chest-dialog').addEventListener('cancel',e=>{e.preventDefault();close()});
 function chestText(){const s=activeChest?.storage||{};$('chest-summary').textContent=Object.entries(s).filter(([k,n])=>n>0).map(([k,n])=>BLOCKS[k]?.name+' ×'+n).join(' · ')||'箱子还是空的。'}
 $('chest-store').onclick=()=>{if(!activeChest)return;activeChest.storage??={};for(let i=1;i<=12;i++){activeChest.storage[i]=(activeChest.storage[i]||0)+(state.bag[i]||0);state.bag[i]=0;}changed();chestText()};$('chest-take').onclick=()=>{if(!activeChest)return;for(let i=1;i<=12;i++){state.add(i,activeChest.storage?.[i]||0);if(activeChest.storage)activeChest.storage[i]=0;}changed();chestText()};
 $('survival-toggle').onclick=()=>{state.setMode(state.survival?'creative':'survival');onMode(state.survival);changed();notify(state.survival?'生存开始！C 制作，Z 吃东西。夜里小心夜影；先做床和石剑。':'已回到创造模式，继续自由搭建。')};
 function use(){const near=closest();if(!near)return false;const a=near.data;if(near.type==='treasure'){state.treasures.add(near.id);state.pearls+=3;state.food+=2;a.root.visible=false;notify('海底发现！海珍珠 +3，食物 +2。');changed();return true;}
  if(near.type==='berry'){if(state.elapsed<a.ready){notify('浆果正在重新生长，稍后再来。');return true;}a.ready=state.elapsed+60;state.food+=2;notify('采到了两份浆果，Z 可以吃。');changed();return true;}
  if(near.type==='animal'){if(a.type==='sheep'&&a.cooldown<=0){state.wool++;a.cooldown=90;notify('羊毛 +1！小羊慢慢长毛中。');}else if(state.food>0){state.food--;a.cooldown=20;a.heading=Math.atan2(a.root.position.x-getPos().x,a.root.position.z-getPos().z)+Math.PI;notify('喂了一份食物，它开心地靠近你。');}else notify('可以喂食、收集羊毛，或者用 Q 打猎。');changed();return true;}
  const f=a.f;if(f.type==='bed'){state.home=[{x:f.x+1.5,y:f.y,z:f.z},{x:f.x-1.5,y:f.y,z:f.z},{x:f.x,y:f.y,z:f.z+1.5},{x:f.x,y:f.y,z:f.z-1.5},{x:f.x,y:f.y+.95,z:f.z}].find(p=>!overlaps(world,p.x,p.y,p.z)&&!furnitureCollides(state.furniture,p.x,p.y,p.z))||null;state.health=20;state.hunger=Math.min(20,state.hunger+2);setDay();notify('睡到天亮，床旁已经设为重生点。');}else if(f.type==='chest'){activeChest=f;chestText();open('chest-dialog');}else if(f.type==='campfire'){if(state.raw){state.food+=state.raw*2;state.raw=0;notify('烤肉完成！每份生肉烤出两份食物。');}else notify('先用 Q 打猎收集生肉，再来烹饪。');}else if(f.type==='planter'){const remaining=Math.max(0,60-(state.elapsed-(f.plantedAt??state.elapsed)));if(remaining>0)notify('菜圃还需要 '+Math.ceil(remaining)+' 秒成熟。');else{state.food+=3;f.plantedAt=state.elapsed;notify('收获蔬菜 +3，已经重新播种。');}}else if(f.type==='chair')notify('在家歇一会儿，今晚的星空很漂亮。');else notify('你的家又丰富了一点。');changed();return true;
 }
 function dive(){if(!state.dive){notify('到东侧码头按 V 免费领取第一套潜水装备，或 C 制作。');return;}state.equipped=!state.equipped;state.oxygen=Math.min(state.oxygen,state.maxOxygen);changed();notify(state.equipped?'潜水套装穿好了：180 秒氧气，更快游泳和更远水下视野。':'已脱下潜水套装。');}
 function dockUse(){if(distance(LANDMARKS.dock)>4)return false;if(!state.dive){state.dive=true;state.equipped=true;state.oxygen=180;changed();notify('领取潜水装备！空格上浮、Shift 下潜。向东南寻找珊瑚、沉船与海底神殿。')}else dive();return true;}
 function eat(){if(state.eat()){changed();notify('吃了一份食物，饱食与体力恢复。')}else notify(state.food?'现在不饿，留着稍后吃吧。':'没有食物了，寻找浆果或用篝火烤肉。');}
 function place(point){if(!state.held)return false;if(!point){notify('对准附近地面再按 E。');return true;}if(state.furniture.length>=200){notify('家具数量已达 200 件');return true;}const f={id:state.furniture.length,type:state.held,x:point.x+.5,y:point.y,z:point.z+.5,rotation:Math.round(getYaw()/(Math.PI/2))*Math.PI/2,storage:{},plantedAt:state.elapsed};const p=getPos(),bounds=furnitureBounds(f);let blocked=false;for(let x=Math.floor(bounds.x1+.02);x<bounds.x2-.02;x++)for(let y=Math.floor(bounds.y1+.02);y<bounds.y2-.02;y++)for(let z=Math.floor(bounds.z1+.02);z<bounds.z2-.02;z++)if(world.get(x,y,z))blocked=true;if(blocked||world.protected(point.x,point.y,point.z)||overlaps(world,f.x,f.y,f.z)||Math.hypot(p.x-f.x,p.z-f.z)<1.2&&Math.abs(p.y-f.y)<2||furnMeshes.some(m=>Math.hypot(m.f.x-f.x,m.f.z-f.z)<1.3&&Math.abs(m.f.y-f.y)<1.8)){notify('这里放不下，请换一处平整空地。');return true;}if(!world.get(point.x,point.y-1,point.z)){notify('家具需要放在实心地面上。');return true;}state.furniture.push(f);furnitureModel(f);state.held=null;changed();notify('家具放好了！靠近按 G 使用，Q 回收。');return true;}
 function occupied(p){return furnMeshes.some(m=>Math.abs(m.f.x-p.x-.5)<.8&&Math.abs(m.f.z-p.z-.5)<.95&&p.y+1>m.f.y&&p.y<m.f.y+1.7)}
 function attack(){for(const e of [...enemies,...animals])if(aimed(e.root,3.6)){e.hp-=state.sword?2:1;if(e.hp<=0){scene.remove(e.root);const enemy=enemies.includes(e),array=enemy?enemies:animals;array.splice(array.indexOf(e),1);if(enemy){state.add(3,2);notify('击退夜影，拾到石头。')}else{state.raw+=2;if(e.type==='sheep')state.wool++;notify('生肉 +2，制作篝火可以烹饪。')}changed();}else notify('命中了！石剑可以一击击退。');return true;}
  const fm=furnMeshes.find(m=>aimed(m.root,3.5));if(fm){if(fm.f.type==='chest'&&Object.values(fm.f.storage||{}).some(n=>n>0)){notify('先取出箱子内的物品再回收。');return true;}packed[fm.f.type]=(packed[fm.f.type]||0)+1;scene.remove(fm.root);furnMeshes.splice(furnMeshes.indexOf(fm),1);state.furniture.splice(state.furniture.indexOf(fm.f),1);if(fm.f.type==='bed')state.home=null;changed();notify('已回收家具，C 背包里可以重新取出。');return true;}return false;
 }
 function spawnEnemy(){if(enemies.length>=6)return;const p=getPos();for(let trial=0;trial<12;trial++){const a=Math.random()*Math.PI*2,x=p.x+Math.sin(a)*(16+Math.random()*9),z=p.z+Math.cos(a)*(16+Math.random()*9),y=ground(x,z);if(x<WORLD_MIN+3||z<WORLD_MIN+3||x>WORLD_MAX-3||z>WORLD_MAX-3||y<=WATER_LEVEL||world.protected(Math.floor(x),y,Math.floor(z))||blocked(x,y,z)||blocked(x,y+.2,z)||Math.hypot(x-LANDMARKS.village.x,z-LANDMARKS.village.z)<12||lit({x,y,z}))continue;const root=new THREE.Group();cube(root,'#42455d',0,.82,0,.65,1.2,.4);cube(root,'#60687e',0,1.62,0,.6,.6,.6);for(const x of [-.16,.16])cube(root,'#b0f0e5',x,1.68,-.31,.12,.12,.06,true);for(const x of [-.22,.22])cube(root,'#34374c',x,.2,0,.2,.4,.2);root.position.set(x,y,z);root.userData.range=70;scene.add(root);enemies.push({root,hp:state.sword?2:3,cooldown:0});return;}}
 function moveCreature(c,dt,speed,heading){const moved=creatureStep(c.root.position,dt,speed,heading,{ground,blocked:(x,y,z)=>blocked(x,y,z)||furnitureCollides(state.furniture,x,y,z),bounds:{min:WORLD_MIN,max:WORLD_MAX},water:WATER_LEVEL});if(moved)c.root.rotation.y=heading;return moved;}
 let previousNight=false;function tick(dt,{night,moving,racing}){if(state.survival&&!racing){state.survivalSeconds+=dt;if(night)state.nightSeconds+=dt;if(previousNight&&!night){if(state.nightSeconds>=20){state.survivalGoals.nights++;notify('平安度过一夜！继续收集材料、种菜和建设你的家。');changed();}state.nightSeconds=0;}}previousNight=night;if(!racing&&state.tick(dt,{underwater:!isDry()&&getPos().y+1.62<WATER_LEVEL,moving})){state.revive();onDeath(state.home);changed();notify('体力耗尽，回到重生点。建筑和背包仍然保留。');}
  for(const a of animals){a.timer-=dt;a.cooldown=Math.max(0,a.cooldown-dt);if(a.timer<=0){a.heading+=(Math.random()-.5)*2.5;a.timer=1.5+Math.random()*4;}if(!moveCreature(a,dt,.55,a.heading)){a.heading+=Math.PI*.7;}for(const [i,leg] of a.legs.entries())leg.rotation.x=Math.sin(state.elapsed*5+i%2*Math.PI)*.24;}
  for(const m of marine){const a=state.elapsed*.14+m.phase;m.root.position.set(m.cx+Math.sin(a)*4,m.y+Math.sin(a*1.6)*.6,m.cz+Math.cos(a)*3);m.root.rotation.y=-a;}
  if(!night){for(const e of enemies)scene.remove(e.root);enemies.length=0;enemyClock=0;}else if(!racing){enemyClock-=dt;if(enemyClock<=0){enemyClock=8;spawnEnemy();}for(const e of enemies){e.cooldown-=dt;const p=getPos(),d=distance(e.root.position);if(d>55){scene.remove(e.root);enemies.splice(enemies.indexOf(e),1);continue;}const a=Math.atan2(e.root.position.x-p.x,e.root.position.z-p.z);if(lit(e.root.position)){moveCreature(e,dt,1.7,a+Math.PI);continue;}if(d>1.4)moveCreature(e,dt,state.survival?1.5:.8,a);else if(e.cooldown<=0&&state.survival&&visiblePoint(e.root.position)){e.cooldown=2;state.hurt(2);notify('夜影袭击！Q 反击，C 制作石剑。');}}}
  for(const m of furnMeshes)if(m.f.type==='planter'){const growth=Math.max(0,Math.min(1,(state.elapsed-(m.f.plantedAt??state.elapsed))/60));for(const crop of m.root.userData.crops){crop.scale.y=.15+growth*.55;crop.position.y=.46+crop.scale.y/2;}}
  hudClock+=dt;if(hudClock>.2){hudClock=0;refresh();const near=closest(),prompt=distance(LANDMARKS.dock)<4?'V 潜水补给 · L 穿脱装备':near?.type==='treasure'?'G 打开海底宝箱':near?.type==='furniture'?RECIPES[near.data.f.type].name+' · G 使用 · Q 回收':near?.type==='berry'?'G 采浆果 · Z 吃东西':near?.type==='animal'?({sheep:'小羊 · G 羊毛 / 喂食',pig:'小猪 · G 喂食',chicken:'小鸡 · G 喂食'}[near.data.type])+' · Q 打猎':'';$('life-prompt').textContent=prompt;$('life-prompt').classList.toggle('visible',!!prompt);}
 }
 function restore(d){for(const m of furnMeshes)scene.remove(m.root);furnMeshes.length=0;for(const e of enemies)scene.remove(e.root);enemies.length=0;state.restore(d);for(let i=0;i<berries.length;i++)berries[i].ready=Number.isFinite(d?.berryReady?.[i])?Math.max(state.elapsed,d.berryReady[i]):0;for(const f of state.furniture)if(f.type==='planter'&&!Number.isFinite(f.plantedAt))f.plantedAt=state.elapsed;for(const key of Object.keys(packed))delete packed[key];for(const [k,n] of Object.entries(d?.packed||{}))if(RECIPES[k]?.item===k&&Number.isInteger(n)&&n>0&&n<999)packed[k]=n;for(const f of state.furniture)furnitureModel(f);for(const [id,t] of treasureMeshes)t.root.visible=!state.treasures.has(id);onMode(state.survival);onHeld(state.held);refresh();}
 function serialize(){return {...state.serialize(),packed:{...packed},berryReady:berries.map(b=>b.ready)}}
 function enterSurvival(){const first=!state.survivalStarted;if(!state.survival)state.setMode('survival');state.survivalStarted=true;onMode(true);changed();notify('生存探索开始：材料有限，C 制作工具，G 采浆果，Z 吃东西；先造床，晚上 Q 反击。');return first;}
 function recordMine(id){if(state.survival&&id===4){state.survivalGoals.wood++;refresh();}}
 refresh();return {enterSurvival,recordMine,state,collides:(x,y,z)=>furnitureCollides(state.furniture,x,y,z),grantGlider:()=>{if(!state.glider){state.glider=true;changed();}},tick,use,dockUse,dive,eat,place,attack,occupied,craft,close,refresh,serialize,restore,isPanelOpen:()=>!!panel,clearHeld:()=>{packHeld();renderPacked()},home:()=>state.home};
}
