import * as THREE from './three.module.js';
import {CITY,PEARL} from './shanghai-map.js';
import {ALL_BUILDINGS} from './city-layout.js';
import {buildingStyle} from './city-architecture.js';
import {showCue} from './show-cues.js';
export function beamCue(time,index){const cue=showCue(time),phase=((cue.beat-index*.25)%1+1)%1,d=Math.min(Math.abs(phase-.16),1-Math.abs(phase-.16));
 return {strength:.025+.975*Math.exp(-((d/.115)**2)),azimuth:Math.PI+(index%5-2)*.32+Math.sin(time*.45+index*.7)*.65,tilt:.3+.75*(.5+.5*Math.sin(time*.7+index*.65)),hue:cue.hue};
}
export function createLujiazuiShow(scene){const root=new THREE.Group();root.name='lujiazui-rhythmic-searchlights';scene.add(root);const beams=[],geometry=new THREE.CylinderGeometry(1,.006,1,12,6,true);geometry.translate(0,.5,0);const color=[];for(let i=0;i<geometry.attributes.position.count;i++){const fade=1-geometry.attributes.position.getY(i)*.85;color.push(fade,fade,fade);}geometry.setAttribute('color',new THREE.Float32BufferAttribute(color,3));
 const positions=[[PEARL.x-8,28,PEARL.z+12],[PEARL.x+8,28,PEARL.z+12],[CITY.jinmao.x-5,101,CITY.jinmao.z],[CITY.jinmao.x+5,101,CITY.jinmao.z],[CITY.swfc.x-4,114,CITY.swfc.z],[CITY.swfc.x+4,114,CITY.swfc.z],[CITY.shanghai.x-3,143,CITY.shanghai.z],[CITY.shanghai.x+3,143,CITY.shanghai.z]];
 for(const b of ALL_BUILDINGS.filter(b=>b.bank==='east'&&b.x<280&&b.z>-40&&b.z<174&&buildingStyle(b).height>=26).filter((b,i)=>i%3===0).slice(0,10))positions.push([b.x+.5,29+buildingStyle(b).height,b.z+.5]);
 for(const [i,[x,y,z]]of positions.entries()){const material=new THREE.MeshBasicMaterial({color:'#6de2ff',vertexColors:true,transparent:true,opacity:.07,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending,fog:false}),cone=new THREE.Mesh(geometry,material),source=new THREE.Vector3(x,y,z);cone.position.copy(source);cone.userData.range=440;root.add(cone);const rays=[cone];for(const side of [-1,1]){const ray=new THREE.Mesh(geometry,material);ray.position.copy(source);ray.userData.range=440;root.add(ray);rays.push(ray);}const light=new THREE.SpotLight('#6de2ff',0,260,.16,.7,1);light.position.copy(source);if(i<8){root.add(light);root.add(light.target);}const housing=new THREE.Mesh(new THREE.CylinderGeometry(.35,.4,.6,8),new THREE.MeshLambertMaterial({color:'#536c76'}));housing.position.copy(source);root.add(housing);beams.push({cone,rays,light,source,housing});}
 let clock=0;function tick(dt,{active=false,time}={}){if(active)clock=time??clock+dt;else clock=0;for(const [i,b]of beams.entries()){for(const ray of b.rays)ray.visible=active;b.light.visible=active;if(!active){b.light.intensity=0;continue;}const cue=beamCue(clock,i),direction=new THREE.Vector3(Math.cos(cue.azimuth)*Math.sin(cue.tilt),Math.cos(cue.tilt),Math.sin(cue.azimuth)*Math.sin(cue.tilt)),length=b.source.y>95?170:220,radius=4.5+(i%3);for(const [j,ray]of b.rays.entries()){const fan=(j===0?0:j===1?-.15:.15),tilt=cue.tilt+fan,azimuth=cue.azimuth+fan*.7,d=new THREE.Vector3(Math.cos(azimuth)*Math.sin(tilt),Math.cos(tilt),Math.sin(azimuth)*Math.sin(tilt));ray.scale.set(radius,length,radius);ray.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d);}b.cone.material.color.setHSL(cue.hue,.72,.68);b.cone.material.opacity=.006+.10*cue.strength;b.light.color.copy(b.cone.material.color);b.light.intensity=35*cue.strength;b.light.target.position.copy(b.source).addScaledVector(direction,length);}}
 tick(0);return {beams,tick};
}
