import * as THREE from './three.module.js';
import {batchMeshes,staticMeshes} from './mesh-batch.js';
import {PRIVATE_SUITES,suiteArrival} from './private-suite-layout.js';
import {decorateSuite} from './suite-decor.js';
import {SuiteControls} from './suite-controls.js';
export function createPrivateSuites({scene,getPos,getState,teleport,lookAt,notify,setDay,onProgress}){
 const root=new THREE.Group();root.name='my-riverfront-suites';scene.add(root);const box=new THREE.BoxGeometry(1,1,1),materials=new Map(),obstacles=[],actions=[],fixtures=[],dynamic=new Set();
 const hint=document.createElement('aside');hint.id='suite-prompt';hint.hidden=true;document.body.append(hint);
 function mat(c,opacity=1){const key=c+opacity;if(!materials.has(key))materials.set(key,new THREE.MeshBasicMaterial({color:c,opacity,transparent:opacity<1,depthWrite:opacity===1}));return materials.get(key);}
 function cube(s,c,x,y,z,w,h,d,solid=false,opacity=1){const m=new THREE.Mesh(box,mat(c,opacity));m.position.set(s.x+.5+x,s.y+y,s.z+.5+z);m.scale.set(w,h,d);root.add(m);if(solid)obstacles.push({x:m.position.x,y:s.y,z:m.position.z,w:w/2+.29,d:d/2+.29,top:m.position.y+h/2});return m;}
 function label(s,text,x,y,z,w=3){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#18303a';ctx.fillRect(0,0,512,96);ctx.fillStyle='#f7e6b5';ctx.textAlign='center';ctx.font='bold 34px sans-serif';ctx.fillText(text,256,60,490);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,.6),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),side:THREE.DoubleSide}));m.position.set(s.x+.5+x,s.y+y,s.z+.5+z);root.add(m);return m;}
 for(const [i,s]of PRIVATE_SUITES.entries()){const wood=i?'#a99780':'#493022',cream='#ede4cf',gold='#cfb47c',bedX=-s.view*(s.rx-1.7),bedZ=-s.rz+2;
  cube(s,'#ece2ce',-s.view*(s.rx-.48),2,0,.06,3.8,s.rz*2-1);cube(s,wood,-s.view*(s.rx-.44),.6,0,.07,1.2,s.rz*2-1);
  for(const z of [-1,1]){cube(s,'#ece2ce',0,2,z*(s.rz-.48),s.rx*2-1,3.8,.06);cube(s,wood,0,.6,z*(s.rz-.44),s.rx*2-1,1.2,.07);cube(s,gold,0,1.23,z*(s.rz-.39),s.rx*2-1,.05,.04);cube(s,'#a49a82',s.view*(s.rx-.35),2,z*(s.rz-1.2),.3,3.6,.5);}
  label({...s,y:26},'V 我的江景套房',s.lobby.x-s.x-.5,2.7,s.lobby.z-s.z+.3,3);
  cube(s,i?'#d3c9b8':'#a28a6b',0,.01,0,s.rx*2-1,.03,s.rz*2-1);cube(s,wood,0,3.85,0,s.rx*2-1,.1,s.rz*2-1);
  if(s.balcony){for(const side of [-1,1])cube(s,'#abd6e2',s.view*s.rx,1.9,side*(s.rz+.7)/2,.04,3.8,s.rz-1.7,false,.11);cube(s,'#abd6e2',-s.rx-1.9,.525,0,.06,1.05,s.rz*2-1,true,.2);cube(s,gold,-s.rx-1.9,1.08,0,.1,.08,s.rz*2-1);for(const side of [-1,1]){cube(s,'#abd6e2',-s.rx-.9,.525,side*(s.rz-.55),2,1.05,.06,true,.2);cube(s,gold,-s.rx-.9,1.08,side*(s.rz-.55),2,.08,.1);}}else cube(s,'#abd6e2',s.view*s.rx,1.9,0,.04,3.8,s.rz*2-1,false,.11);for(const z of [-s.rz+1,s.rz-1])cube(s,gold,s.view*(s.rx-.15),2,z,.12,4,.13);
  cube(s,'#ddd1b9',0,.035,.5,3,.025,3.8);cube(s,i?'#7e8b88':'#725c65',0,.052,.5,2.75,.012,3.5);
  cube(s,wood,bedX,.34,bedZ,2.4,.68,2.5,true);cube(s,cream,bedX,.76,bedZ,2.35,.18,2.45);cube(s,i?'#7b8b8a':'#8b757b',bedX,.87,bedZ+.45,2.35,.05,1.45);cube(s,wood,bedX,1,bedZ-1.2,2.55,1.8,.15);for(const x of [-.55,.55])cube(s,'#fff4db',bedX+x,.94,bedZ-.8,.75,.18,.5);
  cube(s,gold,bedX+.95,1.15,bedZ+1.5,.18,1.1,.18);cube(s,'#fff0bf',bedX+.95,1.75,bedZ+1.5,.5,.4,.5);
  const sofaX=s.view*(s.rx-2),sofaZ=s.rz-2.7;cube(s,cream,sofaX,.5,sofaZ,1.25,.85,2,true);cube(s,cream,sofaX-s.view*.5,.78,sofaZ,.25,.6,2);cube(s,wood,sofaX-s.view*1.45,.5,sofaZ,1,.14,1.1,true);cube(s,gold,sofaX-s.view*1.45,.63,sofaZ,.45,.12,.6);
  cube(s,wood,-s.view*(s.rx-1.2),1.1,1.8,1.5,.18,1.2,true);cube(s,'#263f50',-s.view*(s.rx-1.2),1.5,1.5,.85,.55,.06);cube(s,cream,-s.view*(s.rx-1.2),1,2.7,.6,.2,.6);
  const bathX=-s.view*(s.rx-1.7),bathZ=s.rz-1.6,state=new SuiteControls();
  cube(s,cream,bathX,.32,bathZ,2.3,.14,1.4,true);
  for(const side of [-1,1]){cube(s,cream,bathX+side*1.06,.6,bathZ,.18,.6,1.4);cube(s,cream,bathX,.6,bathZ+side*.61,2,.6,.18);}
  const water=cube(s,'#84c6ce',bathX,.42,bathZ,1.94,.025,1.02,false,.58),stream=cube(s,'#bce5ef',bathX+s.view*.78,.87,bathZ,.045,.55,.045,false,.62);
  cube(s,'#b9c8cc',bathX+s.view*.98,1.04,bathZ,.09,.5,.09);cube(s,'#b9c8cc',bathX+s.view*.86,1.27,bathZ,.3,.07,.09);
  cube(s,'#263039',sofaX-s.view*1.45,.72,sofaZ,.2,.055,.42);for(const z of [-.1,0,.1])cube(s,'#b5c2c6',sofaX-s.view*1.45,.754,sofaZ+z,.065,.014,.045);
  cube(s,wood,s.view*1.3,.88,s.rz-1.4,2,.13,1.2,true);for(const x of [-.5,.5])cube(s,cream,s.view*1.3+x,.95,s.rz-1.4,.45,.02,.45);cube(s,gold,0,3.1,0,.14,.7,.14);for(const x of [-.75,0,.75])cube(s,'#fff0bf',x,2.7,0,.45,.3,.45);
  cube(s,wood,0,1.5,-s.rz+.58,2,3,.15);label(s,'我的江景私邸',0,2.3,-s.rz+.7,2);label(s,'V 电梯 / 返回大堂',0,1.4,-s.rz+.71,1.9);
  decorateSuite(s,i,cube);
  const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const screen=new THREE.Mesh(new THREE.PlaneGeometry(1.86,.81),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));screen.position.set(s.x+.5+s.view*2.7,s.y+2.35,s.z+.5+s.rz-1.015);screen.rotation.y=Math.PI;root.add(screen);
  const fixture={s,state,water,stream,screen,canvas,texture,elapsed:0,screenFrame:-1};fixtures.push(fixture);for(const m of [water,stream,screen])dynamic.add(m);
  actions.push({s,fixture,x:s.x+.5+bathX+s.view*.75,y:s.y,z:s.z+.5+bathZ,kind:'tap'},{s,fixture,x:s.x+.5+bathX+s.view*.75,y:s.y,z:s.z+.5+bathZ-1.8,kind:'drain'},{s,fixture,x:s.x+.5+sofaX-s.view*1.45,y:s.y,z:s.z+.5+sofaZ,kind:'tv'});
  actions.push({s,x:s.x+.5+bedX,y:s.y,z:s.z+.5+bedZ,kind:'rest'},{s,x:s.x+.5,y:s.y,z:s.z-s.rz+1.2,kind:'exit'}, {...s.lobby,s,kind:'enter'});
 }
 function sync(f,force=false){const {state,water,stream}=f;water.visible=state.water>.005;water.position.y=f.s.y+.42+state.water*.35;stream.visible=state.tap&&state.water<1;const frame=state.tv?Math.floor(f.elapsed):-1;if(!force&&frame===f.screenFrame)return;f.screenFrame=frame;const ctx=f.canvas.getContext('2d');ctx.fillStyle=state.tv?'#153144':'#111820';ctx.fillRect(0,0,512,256);if(state.tv){ctx.fillStyle='#72cbd4';for(let k=0;k<12;k++){const h=35+(k*37%79);ctx.fillRect(18+k*40,180-h,28,h);}ctx.fillStyle='#235d76';ctx.fillRect(0,185,512,71);ctx.fillStyle='#7bdce8';for(let k=0;k<7;k++)ctx.fillRect((k*91+frame*9)%512,204+k%3*12,52,2);ctx.fillStyle='#fff0cf';ctx.font='bold 28px sans-serif';ctx.fillText('浦江生活 · LIVE',20,42);ctx.font='18px sans-serif';ctx.fillText('城市慢游 / 江畔风光',20,75);ctx.fillText('今日节目：上海夜景与建筑',20,240);}else{ctx.fillStyle='#69747b';ctx.font='22px sans-serif';ctx.fillText('电视已关闭',196,137);}f.texture.needsUpdate=true;}
 function nearest(){const p=getPos();return actions.map(a=>({...a,d:Math.hypot(a.x-p.x,a.z-p.z)})).filter(a=>Math.abs(p.y-a.y)<1.1&&a.d<(a.kind==='rest'?2.7:a.kind==='exit'?1.1:['tap','drain','tv'].includes(a.kind)?1.9:2)).sort((a,b)=>a.d-b.d)[0];}
 function use(){const a=nearest();if(!a)return false;if(a.fixture){const f=a.fixture;if(a.kind==='tap'){f.state.toggleTap();notify(f.state.tap?'浴缸开始放水，再按 V 关闭水龙头。':'已关闭水龙头。');}else if(a.kind==='drain'){f.state.toggleDrain();notify(f.state.drain?'浴缸开始排水。':'已关闭排水口。');}else{f.state.tv=!f.state.tv;notify(f.state.tv?'电视已打开：浦江生活频道。':'电视已关闭。');}sync(f,true);onProgress();}else if(a.kind==='rest'){const state=getState();state.health=20;state.hunger=20;state.oxygen=state.maxOxygen;setDay();notify('睡了一个安稳的好觉，精神恢复。你的江景套房随时可以从地图返回。');onProgress();}else{teleport(a.kind==='enter'?suiteArrival(a.s):a.s.lobby);lookAt(a.kind==='enter'?a.s.target:{x:a.s.lobby.x+a.s.view*8,y:27.6,z:a.s.z});notify(a.kind==='enter'?'欢迎回到'+a.s.name+'。床边休息，浴缸放水，茶几遥控器开电视：靠近按 V。':'已返回大堂。');}return true;}
 function collides(x,y,z){return obstacles.some(o=>y<o.top&&y+1.75>o.y&&Math.abs(x-o.x)<o.w&&Math.abs(z-o.z)<o.d)||PRIVATE_SUITES.some(s=>y>=s.y-.1&&y<s.y+4&&Math.abs(x-(s.x+.5+s.view*s.rx))<.34&&Math.abs(z-s.z-.5)<s.rz-.3&&(!s.balcony||Math.abs(z-s.z-.5)>1.2));}
 function tick(playing,dt=0){for(const f of fixtures){if(playing){f.state.tick(dt);if(Number.isFinite(dt)&&dt>0)f.elapsed+=dt;}sync(f);}const a=nearest();hint.hidden=!playing||!a;hint.textContent=a?(a.kind==='tap'?'V '+(a.fixture.state.tap?'关闭水龙头':'浴缸放水')+' · 水位 '+Math.round(a.fixture.state.water*100)+'%':a.kind==='drain'?'V '+(a.fixture.state.drain?'关闭排水口':'浴缸排水'):a.kind==='tv'?'V '+(a.fixture.state.tv?'关闭电视':'打开电视'):a.kind==='rest'?'V 在大床上休息':a.kind==='exit'?'V 返回大堂':'V 回到'+a.s.name):'';}
 for(const f of fixtures)sync(f,true);batchMeshes(root,staticMeshes(root,dynamic),'suite-interior');return {root,fixtures,actions,use,collides,tick,serialize:()=>Object.fromEntries(fixtures.map(f=>[f.s.id,f.state.serialize()])),restore:d=>{for(const f of fixtures){f.state.restore(d?.[f.s.id]);sync(f,true);}}};
}
