import * as THREE from './three.module.js';
import {createSkyGradient} from './sky-gradient.js';
export const WEATHER_CYCLE_SECONDS=1200;
export const DAY_CYCLE_SECONDS=1200;
export const WEATHER_TYPES={clear:{name:'晴天',humidity:48,rain:0,fog:0},cloudy:{name:'多云',humidity:73,rain:0,fog:.2},rain:{name:'雨天',humidity:89,rain:1,fog:.48},fog:{name:'江雾',humidity:86,rain:0,fog:1}};
export class WeatherState{
 constructor(){this.mode='auto';this.type='clear';this.elapsed=0;this.cycleSeconds=WEATHER_CYCLE_SECONDS;this.rain=0;this.fog=0;this.cloud=0;this.humidity=48;}
 setMode(mode){if(!['auto','clear','cloudy','rain','fog'].includes(mode))return false;this.mode=mode;if(mode!=='auto')this.type=mode;return true;}
 setCycle(seconds){if(![600,1200,3600].includes(seconds))return false;this.elapsed*=seconds/this.cycleSeconds;this.cycleSeconds=seconds;return true;}
 tick(dt){this.elapsed+=dt;if(this.mode==='auto'){const t=(this.elapsed%this.cycleSeconds)/this.cycleSeconds*400;this.type=t<130?'clear':t<195?'cloudy':t<285?'rain':t<355?'fog':'cloudy';}const spec=WEATHER_TYPES[this.type],a=1-Math.exp(-dt/(this.mode==='auto'?55:7));this.rain+=(spec.rain-this.rain)*a;this.fog+=(spec.fog-this.fog)*a;this.cloud+=((this.type==='clear'?.08:this.type==='cloudy'?.65:.92)-this.cloud)*a;this.humidity+=(spec.humidity-this.humidity)*a;return {name:spec.name,humidity:Math.round(this.humidity),rain:this.rain,fog:this.fog,cloud:this.cloud};}
 serialize(){return {timing:3,cycleSeconds:this.cycleSeconds,mode:this.mode,elapsed:this.elapsed,type:this.type,rain:this.rain,fog:this.fog,cloud:this.cloud,humidity:this.humidity};}
 restore(d){this.mode=['auto','clear','cloudy','rain','fog'].includes(d?.mode)?d.mode:'auto';this.cycleSeconds=d?.timing===3&&[600,1200,3600].includes(d.cycleSeconds)?d.cycleSeconds:WEATHER_CYCLE_SECONDS;const oldCycle=d?.timing===3?([600,1200,3600].includes(d.cycleSeconds)?d.cycleSeconds:WEATHER_CYCLE_SECONDS):d?.timing===2?3600:400;this.elapsed=Number.isFinite(d?.elapsed)?Math.max(0,d.elapsed)*this.cycleSeconds/oldCycle:0;this.type=Object.hasOwn(WEATHER_TYPES,d?.type)?d.type:'clear';this.rain=Number.isFinite(d?.rain)?Math.max(0,Math.min(1,d.rain)):0;this.fog=Number.isFinite(d?.fog)?Math.max(0,Math.min(1,d.fog)):0;this.cloud=Number.isFinite(d?.cloud)?Math.max(0,Math.min(1,d.cloud)):this.rain;this.humidity=Number.isFinite(d?.humidity)?Math.max(0,Math.min(100,d.humidity)):WEATHER_TYPES[this.type].humidity;this.tick(0);}
}
export function createWeather({scene,camera,world,sunBlock,clouds,cloudMat,water,terrainMaterial}){
 const skyGradient=createSkyGradient(scene,camera),state=new WeatherState(),moon=new THREE.Group(),moonMat=new THREE.MeshBasicMaterial({color:'#d4dfeb',transparent:true,opacity:.62,depthWrite:false,fog:false}),moonBody=new THREE.Mesh(new THREE.CircleGeometry(2.3,48),moonMat);moon.name='distant-moon';moon.add(moonBody);
 // A small distant disc avoids a nearby glowing-ball silhouette and artificial volume.
 const craterMat=new THREE.MeshBasicMaterial({color:'#8295b0',transparent:true,opacity:.13,depthWrite:false,fog:false});for(const [x,y,r] of [[-.65,.45,.36],[.55,-.5,.3],[.2,.75,.23],[-.5,-.8,.16]]){const m=new THREE.Mesh(new THREE.CircleGeometry(r,18),craterMat);m.position.set(x,y,.015);moon.add(m);}sunBlock.scale.setScalar(1);sunBlock.material.fog=false;scene.add(moon);moon.children.forEach(m=>m.userData.range=320);sunBlock.userData.range=280;
 const halo=new THREE.Mesh(new THREE.SphereGeometry(8.7,24,14),new THREE.MeshBasicMaterial({color:'#ffc85b',transparent:true,opacity:.14,depthWrite:false,fog:false}));halo.userData.range=280;sunBlock.add(halo);
 const stars=new THREE.Group();for(let i=0;i<38;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.32,.32,.32),new THREE.MeshBasicMaterial({color:'#d9e9ff',fog:false}));const a=i*2.399,y=30+(i*37%115),r=Math.sqrt(180*180-y*y);m.position.set(Math.cos(a)*r,y,Math.sin(a)*r);m.userData.range=280;stars.add(m);}scene.add(stars);
 const count=180,positions=new Float32Array(count*18),geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const rainMat=new THREE.MeshBasicMaterial({color:'#c7e6ed',transparent:true,opacity:.4,side:THREE.DoubleSide,depthWrite:false});const rainMesh=new THREE.Mesh(geometry,rainMat);rainMesh.frustumCulled=false;rainMesh.userData.range=50;scene.add(rainMesh);
 let seed=1731;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const drops=Array.from({length:count},()=>({x:0,y:-100,z:0,roof:0}));
 function reset(d){d.x=camera.position.x+(rand()-.5)*38;d.z=camera.position.z+(rand()-.5)*38;d.y=camera.position.y+5+rand()*18;d.roof=world.ground(Math.floor(d.x),Math.floor(d.z));}
 function tick(dt,dayClock){const info=state.tick(dt),phase=dayClock/240*Math.PI*2,night=Math.sin(phase)<0,alt=Math.abs(Math.sin(phase)),cloudiness=Math.max(info.cloud,info.rain,info.fog*.75);const sunDir=new THREE.Vector3(Math.cos(phase)*125,18+alt*50,-90),elevation=.22+alt*.67,azimuth=phase-Math.PI,moonDir=new THREE.Vector3(Math.cos(azimuth)*Math.cos(elevation),Math.sin(elevation),Math.sin(azimuth)*Math.cos(elevation)).multiplyScalar(245);
  sunBlock.position.copy(camera.position).add(sunDir);sunBlock.lookAt(camera.position);sunBlock.visible=!night&&cloudiness<.8;sunBlock.material.color.set(info.rain>.35?'#cccebd':'#fff6b0');moon.position.copy(camera.position).add(moonDir);moon.lookAt(camera.position);moon.visible=night&&cloudiness<.85;moonMat.opacity=(.35+.27*THREE.MathUtils.smoothstep(alt,0,.4))*(1-cloudiness*.75);craterMat.opacity=moonMat.opacity*.19;stars.position.copy(camera.position);stars.visible=night&&cloudiness<.35;cloudMat.color.set('#586e94').lerp(new THREE.Color('#fffaf0'),THREE.MathUtils.smoothstep(Math.sin(phase),-.12,.45)).lerp(new THREE.Color('#394754').lerp(new THREE.Color('#a7b4bd'),THREE.MathUtils.smoothstep(Math.sin(phase),-.12,.45)),cloudiness);cloudMat.opacity=1;clouds.position.y=info.rain* -8;
  const underwater=camera.position.y<22.25;skyGradient.tick(dayClock,cloudiness,info.fog,!underwater);if(!underwater){const mist=new THREE.Color(night?'#3b4a59':'#b5c5cc');scene.background.copy(skyGradient.horizon).lerp(mist,info.fog*.32+info.rain*.13);scene.fog.color.copy(scene.background);scene.fog.near=48*(1-info.fog)+26*info.fog;scene.fog.far=440*(1-info.fog)+185*info.fog;scene.fog.far-=info.rain*12;}
  terrainMaterial.color.setScalar(1-info.rain*.16);water.material.color.set('#173e5a').lerp(new THREE.Color('#3d9bab'),THREE.MathUtils.smoothstep(Math.sin(phase),-.12,.45)).lerp(new THREE.Color('#627b85'),info.rain*.75+info.fog*.15);rainMesh.visible=info.rain>.04&&!underwater;rainMat.opacity=info.rain*.5;
  if(rainMesh.visible)for(let i=0;i<count;i++){const d=drops[i];d.y-=dt*17;d.x-=dt*.8;if(d.y<Math.max(d.roof,camera.position.y-14)||Math.hypot(d.x-camera.position.x,d.z-camera.position.z)>27)reset(d);const visible=d.y>d.roof&&i<count*info.rain;const x=visible?d.x:0,y=visible?d.y:-200,z=visible?d.z:0,a=i*18;positions.set([x,y,z,x+.045,y,z,x+.2,y+1.3,z,x,y,z,x+.2,y+1.3,z,x+.15,y+1.3,z],a);}
  if(rainMesh.visible)geometry.attributes.position.needsUpdate=true;
  return {...info,night,moonVisible:moon.visible};
 }
 return {state,tick,sun:sunBlock,moon,stars,rainMesh,serialize:()=>state.serialize(),restore:d=>state.restore(d)};
}
