import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {resolve,dirname} from 'node:path';
import {webcrypto} from 'node:crypto';
import worker from '../worker/index.js';
import {storageFixture} from './storage-fixture.mjs';
const require=createRequire(import.meta.url);let canvasLib;try{canvasLib=require(process.env.CANVAS_PACKAGE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');}catch{throw new Error('Runtime QA requires @napi-rs/canvas (set CANVAS_PACKAGE to its installed path).')}
class Element {
 constructor(tag='div'){this.tagName=tag;this.children=[];this.dataset={};this.events={};this.attrs={};this.value=12;this.open=false;const set=new Set();this.classList={add:(...a)=>a.forEach(x=>set.add(x)),remove:(...a)=>a.forEach(x=>set.delete(x)),toggle:(x,v)=>{v??=!set.has(x);v?set.add(x):set.delete(x);return v},contains:x=>set.has(x)};this.style={};}
 addEventListener(type,fn){(this.events[type]??=[]).push(fn)}
 dispatch(type,extra={}){const event={code:type,preventDefault(){},...extra};for(const fn of this.events[type]||[])fn(event)}
 setAttribute(k,v){this.attrs[k]=v} appendChild(c){this.children.push(c);return c} append(...c){this.children.push(...c)} replaceChildren(...c){this.children=c} focus(){} setPointerCapture(){} getBoundingClientRect(){return {left:0,top:0,width:this.width||640,height:this.height||360}} showModal(){this.open=true} close(){this.open=false}
 set innerHTML(v){this.html=v;if(v.includes('infinity')){this.children.push(new Element('span'));this.children.at(-1).className='infinity';}} get innerHTML(){return this.html||''}
 querySelector(s){return s==='.infinity'?this.children.find(c=>c.className==='infinity'):null}
}
class Canvas extends Element {
 constructor(){super('canvas');this._canvas=canvasLib.createCanvas(320,180);}
 get width(){return this._canvas.width} set width(v){this._canvas.width=v} get height(){return this._canvas.height} set height(v){this._canvas.height=v}
 getContext(type){if(type!=='2d')return null;const ctx=this._canvas.getContext('2d');return new Proxy(ctx,{get:(obj,key)=>{if(key==='drawImage')return (img,...args)=>obj.drawImage(img._canvas||img,...args);const v=obj[key];return typeof v==='function'?v.bind(obj):v},set:(obj,key,value)=>{obj[key]=value;return true}})}
 toDataURL(){return this._canvas.toDataURL('image/png')}
}
const html=await readFile(new URL('../game/index.html',import.meta.url),'utf8'),elements=new Map(),buttons=[];
for(const match of html.matchAll(/<([\w-]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=match[1]==='canvas'?new Canvas():new Element(match[1]);if(match[1]==='canvas'){for(const attr of ['width','height']){const size=match[0].match(new RegExp(attr+'="(\\d+)"'));if(size)e[attr]=Number(size[1]);}}e.id=match[2];elements.set(e.id,e);}
for(const match of html.matchAll(/<button([^>]*data-[^>]*)>/g)){const e=new Element('button');for(const m of match[1].matchAll(/data-([\w-]+)(?:="([^"]*)")?/g))e.dataset[m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=m[2]||'';buttons.push(e);}
const document=new Element('document');document.body=new Element('body');document.hidden=false;document.pointerLockElement=null;document.createElement=tag=>tag==='canvas'?new Canvas():new Element(tag);document.createElementNS=(_,tag)=>document.createElement(tag);document.getElementById=id=>{assert(elements.has(id),`Missing HTML element ${id}`);return elements.get(id)};document.querySelectorAll=s=>{const key=s.match(/\[data-([^\]]+)\]/)?.[1]?.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return key?buttons.filter(b=>Object.hasOwn(b.dataset,key)):[]};document.exitPointerLock=()=>{};
const window=new Element('window'),storage=new Map();let now=0,callback;
const {env}=storageFixture();
const context=vm.createContext({document,window,console,innerWidth:640,innerHeight:360,devicePixelRatio:1,matchMedia:()=>({matches:false}),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},performance:{now:()=>now},requestAnimationFrame:fn=>{callback=fn},setTimeout:(fn,ms)=>{const t=setTimeout(fn,ms);t.unref();return t},clearTimeout,setInterval,clearInterval,structuredClone,AbortController,URL,Response,Request,TextEncoder,crypto:webcrypto,Image:canvasLib.Image,skipRender:true,fetch:async(path,opts={})=>worker.fetch(new Request('https://game.test'+path,{...opts,headers:{...opts.headers,Origin:'https://game.test','oai-authenticated-user-id':'qa-player'}}),env)});
const modules=new Map();async function moduleAt(path){if(modules.has(path))return modules.get(path);let code=await readFile(path,'utf8');if(path.endsWith('/game.js'))code+='\nexport {world,pos,life,adventure,captureSave,applySave,physics,teleport,scene,camera,renderer,edit,selected,setFlight,saves,skyline,pendingMine,gliding,toggleGlider,weather,civil,music,lookTowards,companions};';if(path.endsWith('/canvas-renderer.js'))code=code.replace('render(scene,camera){','render(scene,camera){if(globalThis.skipRender)return;');const module=new vm.SourceTextModule(code,{context,identifier:pathToFileURL(path).href});modules.set(path,module);return module;}
const game=await moduleAt(resolve('game/game.js'));await game.link((specifier,ref)=>moduleAt(resolve(dirname(fileURLToPath(ref.identifier)),specifier)));await game.evaluate();const g=game.namespace;await new Promise(r=>setTimeout(r,30));
function press(code){document.dispatch('keydown',{code,repeat:false})}function release(code){document.dispatch('keyup',{code})}function step(seconds){for(let i=0;i<Math.ceil(seconds*60);i++){now+=1000/60;callback(now);}}
// A first-time player can use the festival shortcut directly from the start menu.
elements.get('show-button').onclick();assert.equal(g.pos.x,80.5);assert.equal(g.pos.z,125.5);assert(g.adventure.show.active);elements.get('respawn').onclick();elements.get('look-sun').onclick();elements.get('respawn').onclick();
await elements.get('play').onclick();step(.2);assert.equal(Math.round(g.pos.y),26);assert.equal(g.life.state.mode,'creative');
// A real keyboard route opens crafting, places a bed, sleeps, recalls it and restores it from cloud.
press('KeyC');assert(elements.get('craft-dialog').open);const bedButton=elements.get('recipes').children[1];bedButton.onclick();assert.equal(g.life.state.held,'bed');g.teleport({x:80.5,y:26,z:333.5});g.camera.position.set(80.5,27.62,333.5);g.camera.rotation.set(-.7,0,0);g.camera.updateMatrixWorld();g.edit(true);assert.equal(g.life.state.furniture.length,1,'Bed must place through actual E/aim action');assert.equal(g.life.state.held,null);const bed=g.life.state.furniture[0];g.teleport({x:bed.x+1.5,y:26,z:bed.z});press('KeyG');assert(g.life.state.home,'G sets the bed respawn point');
const saved=g.captureSave();assert.equal(saved.version,6);const furnitureJSON=JSON.stringify(saved.life.furniture.map(({storage,...f})=>f));g.life.state.food=99;g.applySave(saved);assert.equal(JSON.stringify(g.life.state.furniture.map(({storage,...f})=>f)),furnitureJSON);assert.notEqual(g.life.state.food,99);
// Legacy snapshots retain edits and move all player-built blocks up by the world offset.
g.applySave({...saved,version:4,mapRevision:undefined,pos:{x:40,y:10,z:49},edits:[['45,10,54',7]],life:undefined});assert.equal(g.world.get(80,26,334),7);assert.equal(Math.round(g.pos.y),26);assert.equal(g.life.state.furniture.length,0);
// Switching modes disables flight; selected materials become finite.
g.setFlight(true);elements.get('survival-toggle').onclick();assert.equal(g.life.state.mode,'survival');assert.equal(elements.get('mode').textContent,'生存模式');const before=g.pos.y;press('KeyF');step(.1);assert(g.pos.y<=before+.1);
// Dock gear and actual held keyboard movement get the swimmer to the surface.
g.teleport({x:260.5,y:23,z:228.5});press('KeyV');assert(g.life.state.equipped);assert.equal(g.life.state.maxOxygen,180);g.teleport({x:284,y:9,z:287});press('Space');step(4);release('Space');assert(g.pos.y+1.62>22.25,'Head must surface through actual physics');g.teleport({x:284,y:19,z:287});press('ShiftLeft');step(1);release('ShiftLeft');assert(g.pos.y<17,'Shift must descend');assert(g.life.state.oxygen<180);
// Discovering a real treasure uses G, saves once, and is unavailable after restoration.
g.teleport({x:273.5,y:9,z:301.5});press('KeyG');assert(g.life.state.treasures.has('temple'));assert.equal(g.life.state.pearls,3);const underwater=g.captureSave();g.applySave(underwater);press('KeyG');assert.equal(g.life.state.pearls,3);
// Every race option teleports to its own checkpoint and restores a saved active challenge.
g.teleport({x:104.5,y:26,z:350.5});press('KeyV');assert(elements.get('race-dialog').open);elements.get('race-options').children[2].onclick();assert.equal(g.adventure.state.race.course,'cliff');const raceSave=g.captureSave();g.applySave(raceSave);assert.equal(g.adventure.state.race.course,'cliff');assert.equal(g.pos.x,342.5);press('KeyV');assert.equal(g.adventure.state.race,null);
// Completing a race must leave the HUD and game loop working, including the best-time row.
g.teleport({x:104.5,y:26,z:350.5});press('KeyV');elements.get('race-options').children[0].onclick();const course=(await moduleAt(resolve('game/world.js'))).namespace.COURSE;for(const point of course.slice(1)){g.teleport(point);g.adventure.tick(1,g.pos,now/1000);}assert.equal(g.adventure.state.race,null);assert(g.adventure.state.best>0);step(.4);assert(elements.get('best-time').textContent.includes('秒'));
// Shanghai Tower has three working elevator stops and grants a persistent glider at the top.
g.teleport({x:189.5,y:26,z:116.5});press('KeyV');assert(elements.get('elevator-dialog').open);elements.get('elevator-options').children[1].onclick();assert.equal(g.pos.y,86);press('KeyV');elements.get('elevator-options').children[2].onclick();assert.equal(g.pos.y,136);assert(g.life.state.glider);press('KeyP');assert(g.gliding);g.teleport({x:178.5,y:138,z:93.5});step(1);assert(g.pos.y>134,'Glider must arrest the fall');assert(g.pos.y<138);assert(g.captureSave().gliding);press('KeyP');
// Use actual held keyboard input to cross the Nanpu span and climb its approaches.
g.teleport({x:176.5,y:26,z:206.5});g.setFlight(false);g.gliding&&g.toggleGlider();press('KeyW');press('ShiftLeft');press('Space');step(15);release('KeyW');release('ShiftLeft');release('Space');assert(g.pos.x>274,'Bridge input traversal ended at '+JSON.stringify(g.pos));assert(g.pos.y>25,'Bridge traversal must not drop the player into the river');
// New landmark elevators stay in their own building and do not transfer across towers.
for(const [lobby,deck] of [[{x:159.5,y:26,z:71.5},{x:159.5,y:91,z:62.5}],[{x:192.5,y:26,z:56.5},{x:181.5,y:104,z:56.5}]]){g.teleport(lobby);press('KeyV');assert(elements.get('elevator-dialog').open);assert.equal(elements.get('elevator-options').children.length,2);elements.get('elevator-options').children[1].onclick();assert.equal(g.pos.y,deck.y);assert.equal(g.pos.x,deck.x);press('KeyV');elements.get('elevator-options').children[0].onclick();assert.equal(g.pos.y,26);}
// Old Shanghai Tower cloud snapshots migrate their pose without dropping inventory or quests.
const legacySky={...g.captureSave(),mapRevision:undefined,pos:{x:136.5,y:136,z:38.5}};g.applySave(legacySky);assert.equal(g.pos.x,189.5);assert.equal(g.pos.z,106.5);assert.equal(g.pos.y,136);assert(g.life.state.glider);assert.equal(g.captureSave().mapRevision,11);
// Furniture actually stops player movement; collecting behind a stone wall is blocked.
g.teleport({x:80.5,y:26,z:334.5});g.life.state.furniture.push({id:0,type:'table',x:80.5,y:26,z:332.5,storage:{}});press('KeyW');step(1);release('KeyW');assert(g.pos.z>333.3,'Player must not walk through the table');g.life.restore({...g.life.serialize(),furniture:[{id:0,type:'chest',x:80.5,y:26,z:332.5,storage:{7:4}}]});g.teleport({x:80.5,y:26,z:334.5});g.world.set(80,26,333,3);g.world.set(80,27,333,3);g.life.use();assert.equal(elements.get('chest-dialog').open,false,'Walls must block opening the chest');g.world.set(80,26,333,0);g.world.set(80,27,333,0);
// A mature planter yields food once and retains its growth state across restoration.
g.life.restore({...g.life.serialize(),furniture:[{id:0,type:'planter',x:80.5,y:26,z:332.5,plantedAt:g.life.state.elapsed-61,storage:{}}]});g.camera.position.set(80.5,27.62,334.5);g.camera.lookAt(80.5,26.65,332.5);g.camera.updateMatrixWorld();const foodBefore=g.life.state.food;assert(g.life.use());assert.equal(g.life.state.food,foodBefore+3);assert(g.life.use());assert.equal(g.life.state.food,foodBefore+3);g.life.restore(g.life.serialize());assert(g.life.use());assert.equal(g.life.state.food,foodBefore+3);
// Mining has a timed feedback loop, and a stone pick consumes durability on successful collection.
g.life.state.setMode('survival');g.life.state.pickaxe=2;g.life.state.durability=96;g.teleport({x:80.5,y:26,z:334.5});g.world.set(80,26,333,3);g.world.set(80,27,333,3);g.camera.position.set(80.5,27.62,334.5);g.camera.rotation.set(0,0,0);g.camera.updateMatrixWorld();g.edit(false);assert(g.pendingMine);assert.equal(g.world.get(80,27,333),3);step(.4);assert.equal(g.world.get(80,27,333),0);assert.equal(g.life.state.durability,95);g.life.restore({...g.life.serialize(),furniture:[]});g.world.set(80,26,333,0);
// Music can change in both the pause selector and the HUD, preserving the chosen preference.
elements.get('music-choice').value='neon';elements.get('music-choice').dispatch('change',{target:elements.get('music-choice')});assert.equal(g.music.track.id,'neon');elements.get('music-quick').onclick();assert.equal(g.music.track.id,'deep');assert(JSON.parse(storage.get('block-island-music-preferences')).track==='deep');
// Weather selection produces actual droplets, a moon, reduced visibility, and durable save state.
g.teleport({x:112.5,y:26,z:84.5});elements.get('weather-choice').value='rain';elements.get('weather-choice').dispatch('change',{target:elements.get('weather-choice')});step(9);assert(g.weather.rainMesh.visible);assert(g.weather.state.rain>.8);const wetSave=g.captureSave();g.weather.state.setMode('clear');g.applySave(wetSave);assert.equal(g.weather.state.mode,'rain');assert(g.weather.state.rain>.8);elements.get('weather-choice').value='fog';elements.get('weather-choice').dispatch('change',{target:elements.get('weather-choice')});step(15);assert(g.scene.fog.far>175&&g.scene.fog.far<200,'River mist must preserve a useful viewing distance');assert.equal(g.weather.rainMesh.visible,false);g.weather.tick(0,165);assert.equal(g.weather.moon.visible,true);g.weather.state.setMode('clear');g.weather.tick(20,165);assert(g.weather.moon.visible);g.weather.tick(0,36);assert(!g.weather.moon.visible);
// Moving cars and boats stay active on the correct road / river routes.
const oldCar=g.civil.cars[0].z,oldBoat=g.civil.boats[0].z;g.civil.tick(2,{night:false});assert.notEqual(g.civil.cars[0].z,oldCar);assert.notEqual(g.civil.boats[0].z,oldBoat);assert(g.civil.boats.every(b=>b.root.position.y>22&&b.root.position.y<23));
// Walk through every new bank entrance using the actual collision and keyboard loop.
const banks=(await moduleAt(resolve('game/bund.js'))).namespace.BUND_BUILDINGS;
g.life.state.setMode('creative');for(const b of banks){g.teleport({x:b.front+2.5,y:26,z:b.z+.5});g.lookTowards({x:b.x,y:27.62,z:b.z+.5});const backKey='KeyW';press(backKey);step(1.5);release(backKey);assert(g.pos.x<b.front-2,`${b.name} entrance must be walkable`);assert.equal(g.pos.y,26);}
const bridgeCars=g.civil.cars.filter(c=>c.kind==='bridge');assert.equal(bridgeCars.length,4);g.teleport({x:130.5,y:26,z:309.5});const oldX=bridgeCars[1].x;g.civil.tick(2,{night:true});assert.notEqual(bridgeCars[1].x,oldX);for(const c of bridgeCars){assert(g.world.get(Math.floor(c.x),c.root.position.y-1,Math.floor(c.root.position.z)),'Bridge vehicles need solid road beneath them');assert(!g.world.get(Math.floor(c.x),c.root.position.y,Math.floor(c.root.position.z)));assert(g.civil.collides(c.root.position.x,c.root.position.y,c.root.position.z));}
// The dedicated show button moves to a safe viewing spot and aims at a real formation.
elements.get('show-button').onclick();assert.equal(g.pos.x,80.5);assert(g.adventure.show.active);step(16);assert.equal(g.adventure.show.drones.phase,'国庆快乐');assert(g.adventure.show.drones.drones.length>120);for(const d of g.adventure.show.drones.drones)assert(d.mesh.position.distanceTo(d.target)<.15,'Drones must settle into the glyph strokes');
assert(g.captureSave().adventure.state.showWatched);
// A dedicated survival entry continues existing inventory and enables the actual resource loop.
const oldFood=g.life.state.food;g.life.state.survivalStarted=false;await elements.get('start-survival').onclick();assert(g.life.state.survival);assert.equal(g.pos.x,130.5);assert.equal(g.life.state.food,oldFood);assert(!g.captureSave().flying);g.life.recordMine(4);g.life.recordMine(4);g.life.recordMine(4);g.life.tick(25,{night:true,moving:false,racing:false});g.life.tick(.1,{night:false,moving:false,racing:false});assert(g.life.state.survivalGoals.nights>=1);const survival=g.captureSave();g.applySave(survival);assert(g.life.state.survivalGoals.wood>=3);assert(g.life.state.survivalGoals.nights>=1);assert(g.life.state.survivalStarted);
// Version-three landmark snapshots follow the re-spaced towers and relocated diving pier.
g.applySave({...g.captureSave(),mapRevision:3,pos:{x:116.5,y:136,z:85.5}});assert.equal(g.pos.x,189.5);assert.equal(g.pos.z,106.5);g.applySave({...g.captureSave(),mapRevision:3,pos:{x:125.5,y:23,z:118.5}});assert.equal(g.pos.x,260.5);assert.equal(g.pos.z,228.5);
// Previous dock snapshots retain their gear and migrate to the new pier.
g.applySave({...g.captureSave(),mapRevision:2,pos:{x:115.5,y:23,z:118.5}});assert.equal(g.pos.x,260.5);assert.equal(g.pos.y,23);
// Revision-five Bund room poses, furniture and home points migrate to the corrected frontage.
const correctedBanks=(await moduleAt(resolve('game/city-layout.js'))).namespace.BUND_BUILDINGS,oldCustomsX=52,newCustoms=correctedBanks.find(b=>b.id==='customs');
g.applySave({...g.captureSave(),mapRevision:5,pos:{x:oldCustomsX+.5,y:26,z:60.5},life:{...g.life.serialize(),furniture:[{id:91,type:'chest',x:oldCustomsX+2.5,y:26,z:62.5,storage:{7:11}}],home:{x:oldCustomsX+2,y:26,z:60}}});assert.equal(g.pos.x,newCustoms.x+.5);assert.equal(g.pos.z,newCustoms.z+.5);assert.equal(g.life.state.furniture[0].x,newCustoms.x+2.5);assert.equal(g.life.state.furniture[0].storage[7],11);assert.equal(g.life.state.home.z,newCustoms.z);
const walker=g.civil.pedestrians.find(p=>p.kind==='walk'),oldWalk=walker.root.position.clone();g.civil.tick(2,{night:false});assert(walker.root.position.distanceTo(oldWalk)>.5);assert(g.civil.pedestrians.some(p=>p.kind==='photo'&&p.camera.visible));assert(g.civil.pedestrians.every(p=>p.root.parent===g.scene),'Animated visitors must survive static geometry batching');
// Current revision four homes, furniture, chest contents and custom blocks migrate together.
const homeSave={...g.captureSave(),mapRevision:4,pos:{x:40,y:26,z:49},edits:[['45,26,54',7]],life:{...g.life.serialize(),furniture:[{id:91,type:'chest',x:45.5,y:26,z:54.5,storage:{7:23}}],home:{x:47,y:26,z:54}}};g.applySave(homeSave);assert.equal(g.pos.x,75);assert.equal(g.pos.z,329);assert.equal(g.world.get(80,26,334),7);assert.equal(g.life.state.furniture[0].x,80.5);assert.equal(g.life.state.furniture[0].z,334.5);assert.equal(g.life.state.furniture[0].storage[7],23);assert.equal(g.life.state.home.z,334);assert(g.companions.npcs.every(n=>n.home.z>300));
// Automatic lights require only ordinary nightfall, without a festival launch.
// Save and restore a player, construction, chest and home beyond the former zero boundary.
g.teleport({x:-149.5,y:26,z:-46.5});g.life.restore({...g.life.serialize(),furniture:[{id:92,type:'chest',x:-149.5,y:26,z:-45.5,storage:{7:19}}],home:{x:-149.5,y:26,z:-46.5}});
g.world.set(-149,26,-50,7);const northSave={...g.captureSave(),edits:[['-149,26,-50',7]]};g.applySave(northSave);assert.equal(g.pos.z,-46.5);assert.equal(g.world.get(-149,26,-50),7);assert.equal(g.life.state.furniture[0].storage[7],19);assert.equal(g.life.state.home.z,-46.5);
step(43);g.applySave({...g.captureSave(),dayClock:36});step(.1);assert(g.civil.windows.every(m=>!m.visible));assert(g.civil.facadeLights.every(m=>!m.visible));assert(g.skyline.lines.every(m=>!m.visible));assert(g.adventure.show.leds.every(m=>!m.visible));g.applySave({...g.captureSave(),dayClock:165});step(.1);assert(g.civil.windows.some(m=>m.visible));assert(g.civil.windows.some(m=>!m.visible));assert(g.civil.facadeLights.every(m=>m.visible));assert(g.skyline.lines.every(m=>m.visible));assert(g.adventure.show.leds.every(m=>m.visible));
// Night actually creates enemies; daytime removes them. Render real models and software frames.
g.teleport({x:75,y:26,z:329});for(let i=0;i<8;i++)g.life.tick(9,{night:true,moving:false,racing:false});assert(g.scene.children.some(o=>o.isGroup&&o.children.some(c=>c.material?.color?.getHexString()==='42455d')),'Night enemies should spawn');g.life.tick(.1,{night:false,moving:false,racing:false});assert(!g.scene.children.some(o=>o.isGroup&&o.children.some(c=>c.material?.color?.getHexString()==='42455d')));
context.skipRender=false;g.teleport({x:120,y:90,z:232});g.camera.position.set(120,91.62,232);g.camera.lookAt(162,65,64);g.scene.background.set('#9fd4e8');g.scene.fog.color.set('#9fd4e8');g.scene.fog.near=48;g.scene.fog.far=270;g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-shanghai.png',elements.get('world')._canvas.toBuffer('image/png'));g.teleport({x:91,y:45,z:145});g.camera.position.set(91,46.62,145);g.camera.lookAt(146,39,106);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-bridge.png',elements.get('world')._canvas.toBuffer('image/png'));g.teleport({x:69,y:27,z:339});g.camera.position.set(69,28.62,339);g.camera.lookAt(77,27.8,327);g.scene.background.set('#9fd4e8');g.scene.fog.color.set('#9fd4e8');g.scene.fog.near=48;g.scene.fog.far=110;g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-land.png',elements.get('world')._canvas.toBuffer('image/png'));g.teleport({x:274,y:12,z:312});g.camera.position.set(274,13.62,312);g.camera.lookAt(278,11,295);g.scene.background.set('#3296a7');g.scene.fog.color.set('#3296a7');g.scene.fog.near=0;g.scene.fog.far=55;g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-sea.png',elements.get('world')._canvas.toBuffer('image/png'));
g.teleport({x:65,y:86,z:60});g.camera.position.set(65,87.62,60);g.camera.lookAt(164,76,66);g.scene.background.set('#9fd4e8');g.scene.fog.color.set('#9fd4e8');g.scene.fog.near=48;g.scene.fog.far=270;g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-trio.png',elements.get('world')._canvas.toBuffer('image/png'));g.adventure.map();await writeFile('/tmp/island-map.png',elements.get('large-map')._canvas.toBuffer('image/png'));g.adventure.close();
g.teleport({x:140,y:58,z:100});g.camera.position.set(140,59.62,100);g.camera.lookAt(79,36,82);g.weather.state.setMode('clear');g.weather.tick(20,36);g.scene.background.set('#9fd4e8');g.scene.fog.color.set('#9fd4e8');g.scene.fog.near=48;g.scene.fog.far=270;g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-bund.png',elements.get('world')._canvas.toBuffer('image/png'));g.teleport({x:112,y:26,z:84});g.camera.position.set(112,27.62,84);g.camera.lookAt(160,75,65);g.weather.state.setMode('rain');g.weather.tick(20,36);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-rain.png',elements.get('world')._canvas.toBuffer('image/png'));g.weather.state.setMode('fog');g.weather.tick(20,36);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-fog.png',elements.get('world')._canvas.toBuffer('image/png'));
context.skipRender=true;elements.get('show-button').onclick();step(17);context.skipRender=false;g.weather.state.setMode('clear');g.weather.tick(20,165);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-drones.png',elements.get('world')._canvas.toBuffer('image/png'));
for(const [id,name]of [['look-sun','sun'],['look-moon','moon']]){context.skipRender=true;elements.get(id).onclick();step(.05);context.skipRender=false;const orb=name==='moon'?g.weather.moon:g.weather.sun;assert(orb?.visible);assert.equal((name==='sun'?orb:orb.children[0]).geometry.type,'SphereGeometry');if(name==='sun')assert.equal(orb.material.fog,false,'The sun must not disappear into distance fog');const skyRay=orb.position.clone().sub(g.camera.position),skyDistance=skyRay.length();const tracer=(await moduleAt(resolve('game/world.js'))).namespace.trace;assert.equal(tracer(g.world,g.camera.position,skyRay.normalize(),skyDistance-8),null,'Buildings must not block the selected sun or moon viewing spot');const projected=orb.position.clone().project(g.camera);assert(Math.abs(projected.x)<.02&&Math.abs(projected.y)<.02,'Celestial viewing buttons must center the actual sky object');g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-'+name+'.png',elements.get('world')._canvas.toBuffer('image/png'));}
context.skipRender=true;step(43);g.applySave({...g.captureSave(),dayClock:165});step(.1);context.skipRender=false;g.teleport({x:130,y:45,z:30});g.camera.position.set(130,46.62,30);g.camera.lookAt(72,36,91);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-bund-night.png',elements.get('world')._canvas.toBuffer('image/png'));g.teleport({x:65,y:86,z:60});g.camera.position.set(65,87.62,60);g.camera.lookAt(164,76,66);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-trio-night.png',elements.get('world')._canvas.toBuffer('image/png'));
const lobby=banks.find(b=>b.id==='avenue-0');g.teleport({x:lobby.x+4.5,y:26,z:lobby.z+.5});g.camera.position.set(g.pos.x,27.62,g.pos.z);g.camera.lookAt(lobby.x-3,27.6,lobby.z);g.renderer.last=0;g.renderer.render(g.scene,g.camera);await writeFile('/tmp/island-bank.png',elements.get('world')._canvas.toBuffer('image/png'));
await elements.get('save-game').onclick();const list=await (await context.fetch('/api/saves')).json();assert(list.saves.length>0);const cloud=await (await context.fetch('/api/saves/'+list.saves[0].id)).json();assert(cloud.life.glider);assert(cloud.skyline.visited);g.life.state.glider=false;assert(await g.saves.continueLatest());assert(g.life.state.glider,'Default continuation must restore the saved island');
console.log('PASS: race completion HUD, Shanghai Tower elevator/glider, furniture collision and wall occlusion, crop growth and saved harvesting, timed mining/tool durability, new equipment cloud round-trip, full game startup and real inputs, bed crafting/placement/use, version 4 migration, furniture save/restore, finite survival/flight guard, dock equipment, underwater ascent/descent, treasure persistence, race chooser/save/exit, real nighttime enemy lifecycle and rendered land/underwater frames.');
