import assert from 'node:assert/strict';
import {VoxelWorld,SIZE,WORLD_MIN,WORLD_MAX,HEIGHT,BLOCKS,LANDMARKS,COURSES,COURSE,CRYSTALS,WORLD_SHIFT,WATER_LEVEL,overlaps,trace} from '../game/world.js';
import {AdventureState} from '../game/adventure-state.js';
import {SurvivalState,swimVelocity,furnitureCollides} from '../game/survival-state.js';
const world=new VoxelWorld();
assert.equal(SIZE,624);assert.equal(WORLD_MIN,-224);assert.equal(WORLD_MAX,400);assert.equal(HEIGHT,144);assert(world.data.every(v=>v<BLOCKS.length));assert.equal(WORLD_SHIFT,16);
for(const [id,p] of Object.entries(LANDMARKS)){assert(!overlaps(world,p.x,p.y,p.z),`Unsafe landmark: ${id}`);assert(overlaps(world,p.x,p.y-.1,p.z),`No floor at ${id}`)}
for(const c of COURSES)for(const [i,p] of c.platforms.entries()){assert(!overlaps(world,p.x,p.y,p.z),`Course ${c.id} ${i} obstructed`);assert(overlaps(world,p.x,p.y-.1,p.z));if(i){const prev=c.platforms[i-1];assert(p.y-prev.y<=1);const widths=p.radius+prev.radius+1+.58;const gap=Math.hypot(Math.max(0,Math.abs(p.x-prev.x)-widths),Math.max(0,Math.abs(p.z-prev.z)-widths));const time=(8+Math.sqrt(64-2*23*(p.y-prev.y)))/23;assert(gap<time*(c.sprint?7:4.5),`Gap ${c.id} ${i} cannot be jumped (${gap})`)}}
for(const c of CRYSTALS)assert(!overlaps(world,c.x,c.y-1.5,c.z),`Crystal ${c.id} intersects a solid`);
assert(world.protected(126,42,42));assert(world.protected(92,28,325));assert(!world.protected(80,26,329));
const quest=new AdventureState();assert.equal(quest.collectAt({x:93,y:26,z:329}).length,0);quest.painted=true;assert.equal(quest.collectAt({x:93,y:26,z:329}).length,1);assert.equal(quest.collectAt({x:93,y:26,z:329}).length,0);
for(const c of CRYSTALS)quest.collectAt({x:c.x,y:c.y-.9,z:c.z});assert(quest.completed);
for(const c of COURSES){quest.startRace(true,c.id);assert.equal(quest.stepRace(.1,c.platforms.at(-1)),null,'Cannot skip checkpoints');assert.equal(quest.race.checkpoint,0);const fall=quest.stepRace(.2,{x:c.start.x,y:c.fallY-1,z:c.start.z});assert.equal(fall.type,'fall');assert.equal(fall.point,c.start);for(const p of c.platforms.slice(1)){const result=quest.stepRace(1,p);if(p===c.platforms.at(-1)){assert.equal(result.type,'finish');assert.equal(result.restoreFlight,true)}}assert(quest.bestTimes[c.id]>0);}
const restored=new AdventureState();restored.restore(quest.serialize());assert(restored.completed);assert.deepEqual(restored.bestTimes,quest.bestTimes);assert.equal(restored.best,quest.best);
const hit=trace(world,{x:75.5,y:28,z:329.5},{x:0,y:-1,z:0});assert.equal(hit.y,25);assert.equal(hit.place.y,26);
// Run the exact swimming velocity used by gameplay through the voxel collision solver.
let y=9,vy=0,maxY=y;for(let i=0;i<1200;i++){vy=swimVelocity({feet:y,velocity:vy,space:true,down:false,grounded:false,dt:1/120});const next=y+vy/120;if(!overlaps(world,284,y,287)&&!overlaps(world,284,next,287))y=next;else vy=0;maxY=Math.max(maxY,y);}assert(maxY>WATER_LEVEL+.7,'Space must lift the swimmer above the surface and dock edge');
let diverY=WATER_LEVEL-2;for(let i=0;i<120;i++){const v=swimVelocity({feet:diverY,velocity:0,space:false,down:true,grounded:false,dt:1/120});diverY+=v/120;}assert(diverY<WATER_LEVEL-5,'Shift must descend');
const survival=new SurvivalState();survival.setMode('survival');assert(survival.consume(7));assert(!survival.craft('bed'),'A survival bed needs wool');survival.wool=1;assert(survival.craft('bed'));assert.equal(survival.wool,0);assert.equal(survival.held,'bed');assert(!survival.craft('chair'),'Cannot overwrite held furniture');survival.held=null;survival.bag[3]=0;assert(!survival.craft('sword'));survival.add(3,4);assert(survival.craft('sword'));survival.hunger=8;assert(survival.eat());assert.equal(survival.hunger,14);survival.oxygen=1;survival.health=20;for(let i=0;i<6;i++)survival.tick(1,{underwater:true,moving:true});assert(survival.health<20);survival.dive=true;survival.equipped=true;survival.oxygen=180;for(let i=0;i<60;i++)survival.tick(1,{underwater:true});assert.equal(survival.oxygen,120);assert(survival.health>0);survival.furniture.push({id:0,type:'chest',x:45.5,y:26,z:54.5,storage:{7:8}});survival.treasures.add('reef');survival.home={x:45,y:26,z:54};const restoredLife=new SurvivalState();restoredLife.restore(survival.serialize());assert.deepEqual(restoredLife.furniture,survival.furniture.map(f=>({...f,storage:Object.fromEntries(Array.from({length:12},(_,i)=>[i+1,f.storage[i+1]||0]))})));assert(restoredLife.treasures.has('reef'));assert(restoredLife.sword);assert.equal(restoredLife.maxOxygen,180);restoredLife.setMode('creative');restoredLife.health=20;restoredLife.hurt(100);assert.equal(restoredLife.health,20);assert(restoredLife.consume(12));
assert(survival.miningTime(3)>0);survival.setMode('survival');survival.bag[3]=8;survival.bag[4]=4;assert(survival.craft('stonepick'));assert.equal(survival.durability,96);assert.equal(survival.miningTime(3),.24);survival.durability=1;assert(!survival.useTool());assert.equal(survival.pickaxe,0);assert(survival.craft('planter'));const furniture=[{type:'table',x:45.5,y:26,z:54.5}];assert(furnitureCollides(furniture,45.5,26,54.5));assert(!furnitureCollides(furniture,47,26,54.5));assert(!furnitureCollides(furniture,45.5,28,54.5));
console.log('PASS: 624-square expanded world, 66 physically reachable varied parkour checkpoints, landmark safety, legacy coordinate offset, water ascent/descent, survival recipes, oxygen/drowning, equipment, furniture/storage restoration and creative mode.');
